! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc2006_Rates.f90
! Time                 : Tue Jul 14 14:49:18 2015
! Working directory    : /home/mahesh/Software/kpp-2.2.3/tmp/saprc
! Equation file        : saprc2006.kpp
! Output root filename : saprc2006
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc2006_Rates

  USE saprc2006_Parameters
  USE saprc2006_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE saprc2006_Parameters
      !USE saprc2006_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (1.0*SUN)
  RCONST(2) = (ARR(5.68e-34,0.0,-2.80))
  RCONST(3) = (ARR(8.00e-12,2060.0,0.0))
  RCONST(4) = (ARR(1.00e-31,0.0,-1.60))
  RCONST(5) = (ARR(6.50e-12,-120.0,0.0))
  RCONST(6) = (FALL(9.00e-32,0.0,-2.00,2.20e-11,0.0,0.0,0.80))
  RCONST(7) = (ARR(1.80e-12,1370.0,0.0))
  RCONST(8) = (ARR(1.40e-13,2470.0,0.0))
  RCONST(9) = (ARR(1.80e-11,-110.0,0.0))
  RCONST(10) = (ARR(3.30e-39,-530.0,0.0))
  RCONST(11) = (FALL(2.80e-30,0.0,-3.50,2.00e-12,0.0,0.20,0.45))
  RCONST(12) = (FALL(1.e-3,11000.0,-3.5,9.7e14,11080.0,0.1,0.45))
  RCONST(13) = ((2.60e-22))
  RCONST(14) = (ARR(4.50e-14,1260.0,0.0))
  RCONST(15) = (1.0*SUN)
  RCONST(16) = (1.0*SUN)
  RCONST(17) = (1.0*SUN)
  RCONST(18) = (1.0*SUN)
  RCONST(19) = ((2.20e-10))
  RCONST(20) = (ARR(2.09e-11,-95.0,0.0))
  RCONST(21) = (FALL(7.00e-31,0.0,-2.60,3.60e-11,0.0,-0.10,0.60))
  RCONST(22) = (1.0*SUN)
  RCONST(23) = (1.0*SUN)
  RCONST(24) = (ARR(2.70e-12,-260.0,0.0))
  RCONST(25) = (FALL(2.43e-30,0.0,-3.10,1.67e-11,0.0,-2.10,0.60))
  RCONST(26) = ((2.00e-11))
  RCONST(27) = (EP2(7.20e-15,-785.0,4.10e-16,-1440.0,1.90e-33,-725.0))
  RCONST(28) = (1.0*SUN)
  RCONST(29) = (EP3(1.30e-13,0.0,3.19e-33,0.0))
  RCONST(30) = (ARR(1.90e-12,1000.0,0.0))
  RCONST(31) = (ARR(3.40e-12,-270.0,0.0))
  RCONST(32) = (FALL(1.80e-31,0.0,-3.20,4.70e-12,0.0,0.0,0.60))
  RCONST(33) = (FALL(4.10e-05,10650.0,0.0,5.7e+15,11170.0,0.0,0.5))
  RCONST(34) = (1.0*SUN)
  RCONST(35) = (ARR(1.50e-12,-360.0,0.0))
  RCONST(36) = (ARR(1.40e-14,600.0,0.0))
  RCONST(37) = (EP3(2.20e-13,-600.0,1.85e-33,-980.0))
  RCONST(38) = (EP3(3.08e-34,-2800.0,2.59e-38,-3180.0))
  RCONST(39) = ((4.00e-12))
  RCONST(40) = (ARR(8.50e-13,2450.0,0.0))
  RCONST(41) = (1.0*SUN)
  RCONST(42) = (ARR(2.90e-12,160.0,0.0))
  RCONST(43) = (ARR(4.80e-11,-250.0,0.0))
  RCONST(44) = (FALL(4.00e-31,0.0,-3.30,2.00e-12,0.0,0.0,0.45))
  RCONST(45) = (ARR(7.70e-12,2100.0,0.0))
  RCONST(46) = (ARR(2.80e-12,-285.0,0.0))
  RCONST(47) = (ARR(3.80e-13,-780.0,0.0))
  RCONST(48) = ((1.30e-12))
  RCONST(49) = (ARR(2.45e-14,-710.0,0.0))
  RCONST(50) = (ARR(5.90e-13,509.0,0.0))
  RCONST(51) = (ARR(2.70e-12,-360.0,0.0))
  RCONST(52) = (ARR(1.90e-13,-1300.0,0.0))
  RCONST(53) = ((2.30e-12))
  RCONST(54) = ((2.00e-13))
  RCONST(55) = ((3.50e-14))
  RCONST(56) = (ARR(2.70e-12,-360.0,0.0))
  RCONST(57) = (ARR(1.90e-13,-1300.0,0.0))
  RCONST(58) = ((2.30e-12))
  RCONST(59) = ((2.00e-13))
  RCONST(60) = ((3.50e-14))
  RCONST(61) = ((0.0))
  RCONST(62) = (ARR(2.70e-12,-360.0,0.0))
  RCONST(63) = (ARR(1.90e-13,-1300.0,0.0))
  RCONST(64) = ((2.00e-13))
  RCONST(65) = ((2.30e-12))
  RCONST(66) = ((3.50e-14))
  RCONST(67) = ((3.50e-14))
  RCONST(68) = ((3.50e-14))
  RCONST(69) = (FALL(2.70e-28,0.0,-7.10,1.20e-11,0.0,-0.90,0.30))
  RCONST(70) = (FALL(4.90e-3,12100.0,0.0,4.0e+16,13600.0,0.,0.3))
  RCONST(71) = (ARR(7.80e-12,-300.0,0.0))
  RCONST(72) = (ARR(4.30e-13,-1040.0,0.0))
  RCONST(73) = ((4.00e-12))
  RCONST(74) = (ARR(1.80e-12,-500.0,0.0))
  RCONST(75) = ((7.50e-12))
  RCONST(76) = ((7.50e-12))
  RCONST(77) = ((7.50e-12))
  RCONST(78) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(79) = (ARR(1.20e-11,0.0,-0.90))
  RCONST(80) = (ARR(2.00e+15,12800.0,0.0))
  RCONST(81) = (ARR(1.25e-11,-240.0,0.0))
  RCONST(82) = (ARR(4.30e-13,-1040.0,0.0))
  RCONST(83) = ((4.00e-12))
  RCONST(84) = (ARR(1.80e-12,-500.0,0.0))
  RCONST(85) = ((7.50e-12))
  RCONST(86) = ((7.50e-12))
  RCONST(87) = ((7.50e-12))
  RCONST(88) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(89) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(90) = ((1.37e-11))
  RCONST(91) = (ARR(7.90e+16,14000.0,0.0))
  RCONST(92) = (ARR(1.25e-11,-240.0,0.0))
  RCONST(93) = (ARR(4.30e-13,-1040.0,0.0))
  RCONST(94) = ((4.00e-12))
  RCONST(95) = (ARR(1.80e-12,-500.0,0.0))
  RCONST(96) = ((7.50e-12))
  RCONST(97) = ((7.50e-12))
  RCONST(98) = ((7.50e-12))
  RCONST(99) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(100) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(101) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(102) = (ARR(1.20e-11,0.0,-0.90))
  RCONST(103) = (ARR(1.60e+16,13486.0,0.0))
  RCONST(104) = (ARR(1.25e-11,-240.0,0.0))
  RCONST(105) = (ARR(4.30e-13,-1040.0,0.0))
  RCONST(106) = ((4.00e-12))
  RCONST(107) = (ARR(1.80e-12,-500.0,0.0))
  RCONST(108) = ((7.50e-12))
  RCONST(109) = ((7.50e-12))
  RCONST(110) = ((7.50e-12))
  RCONST(111) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(112) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(113) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(114) = (ARR(2.90e-12,-500.0,0.0))
  RCONST(115) = ((2.40e-11))
  RCONST(116) = (ARR(7.50e+14,8152.0,0.0))
  RCONST(117) = (ARR(2.30e-11,-150.0,0.0))
  RCONST(118) = (ARR(1.90e-13,-1300.0,0.0))
  RCONST(119) = ((1.00e-03))
  RCONST(120) = (ARR(7.50e+14,8152.0,0.0))
  RCONST(121) = (ARR(2.30e-11,-150.0,0.0))
  RCONST(122) = (ARR(1.90e-13,-1300.0,0.0))
  RCONST(123) = (1.0*SUN)
  RCONST(124) = (1.0*SUN)
  RCONST(125) = (ARR(8.60e-12,-20.0,0.0))
  RCONST(126) = (ARR(9.70e-15,-625.0,0.0))
  RCONST(127) = (ARR(2.40e+12,7000.0,0.0))
  RCONST(128) = (ARR(2.80e-12,-285.0,0.0))
  RCONST(129) = (ARR(2.00e-12,2431.0,0.0))
  RCONST(130) = (ARR(5.60e-12,-310.0,0.0))
  RCONST(131) = (1.0*SUN)
  RCONST(132) = (ARR(1.40e-12,1860.0,0.0))
  RCONST(133) = ((2.00e-11))
  RCONST(134) = (1.0*SUN)
  RCONST(135) = (ARR(1.40e-12,1771.0,0.0))
  RCONST(136) = (ARR(1.10e-12,520.0,0.0))
  RCONST(137) = (1.0*SUN)
  RCONST(138) = (ARR(1.30e-12,25.0,2.0))
  RCONST(139) = (1.50e-1*SUN)
  RCONST(140) = (ARR(3.10e-12,360.0,2.0))
  RCONST(141) = (ARR(0.0,0.0,1.0))
  RCONST(142) = (ARR(2.90e-12,-190.0,0.0))
  RCONST(143) = (1.0*SUN)
  RCONST(144) = ((1.10e-11))
  RCONST(145) = (1.0*SUN)
  RCONST(146) = (1.0*SUN)
  RCONST(147) = (6.00e-3*SUN)
  RCONST(148) = ((1.10e-11))
  RCONST(149) = (ARR(2.80e-12,2376.0,0.0))
  RCONST(150) = (1.0*SUN)
  RCONST(151) = ((1.50e-11))
  RCONST(152) = (ARR(1.40e-12,1895.0,0.0))
  RCONST(153) = (1.0*SUN)
  RCONST(154) = ((2.63e-11))
  RCONST(155) = ((3.78e-12))
  RCONST(156) = ((4.20e-11))
  RCONST(157) = ((1.37e-11))
  RCONST(158) = ((2.63e-11))
  RCONST(159) = ((1.29e-11))
  RCONST(160) = (5.00e-2*SUN)
  RCONST(161) = (ARR(1.40e-12,1872.0,0.0))
  RCONST(162) = (ARR(1.86e-11,-176.0,0.0))
  RCONST(163) = (ARR(1.36e-15,2114.0,0.0))
  RCONST(164) = (ARR(1.50e-12,1726.0,0.0))
  RCONST(165) = ((6.34e-12))
  RCONST(166) = (4.10e-3*SUN)
  RCONST(167) = (ARR(4.14e-12,-453.0,0.0))
  RCONST(168) = (ARR(7.51e-16,1520.0,0.0))
  RCONST(169) = ((4.32e-12))
  RCONST(170) = (2.10e-3*SUN)
  RCONST(171) = ((6.19e-11))
  RCONST(172) = ((4.18e-18))
  RCONST(173) = ((1.00e-13))
  RCONST(174) = (4.10e-3*SUN)
  RCONST(175) = ((1.50e-11))
  RCONST(176) = (2.00e-2*SUN)
  RCONST(177) = ((7.80e-12))
  RCONST(178) = (1.0*SUN)
  RCONST(179) = ((5.00e-11))
  RCONST(180) = ((2.00e-18))
  RCONST(181) = ((5.00e-11))
  RCONST(182) = (3.65e-1*SUN)
  RCONST(183) = ((5.00e-11))
  RCONST(184) = (7.28*SUN)
  RCONST(185) = (ARR(2.15e-12,1735.0,0.0))
  RCONST(186) = (ARR(1.96e-12,-438.0,0.0))
  RCONST(187) = (ARR(9.14e-15,2580.0,0.0))
  RCONST(188) = (ARR(4.39e-13,2282.0,2.0))
  RCONST(189) = (ARR(1.04e-11,792.0,0.0))
  RCONST(190) = (ARR(2.50e-11,-408.0,0.0))
  RCONST(191) = (ARR(7.86e-15,1912.0,0.0))
  RCONST(192) = (ARR(3.03e-12,448.0,0.0))
  RCONST(193) = ((3.60e-11))
  RCONST(194) = (ARR(1.83e-11,-449.0,0.0))
  RCONST(195) = (ARR(1.08e-15,821.0,0.0))
  RCONST(196) = (ARR(3.66e-12,-175.0,0.0))
  RCONST(197) = ((3.27e-11))
  RCONST(198) = (ARR(1.37e-12,498.0,2.0))
  RCONST(199) = (ARR(0.0,0.0,1.0))
  RCONST(200) = (ARR(9.87e-12,671.0,0.0))
  RCONST(201) = (ARR(1.019e-11,434.0,0.0))
  RCONST(202) = (ARR(5.946e-12,91.0,0.0))
  RCONST(203) = (ARR(1.112e-11,52.0,0.0))
  RCONST(204) = (ARR(1.81e-12,-355.0,0.0))
  RCONST(205) = ((2.640e-11))
  RCONST(206) = (ARR(7.095e-12,-451.0,0.0))
  RCONST(207) = (ARR(2.617e-15,1640.0,0.0))
  RCONST(208) = (ARR(4.453e-14,376.0,0.0))
  RCONST(209) = (ARR(1.074e-11,234.0,0.0))
  RCONST(210) = (ARR(1.743e-11,-384.0,0.0))
  RCONST(211) = (ARR(5.022e-16,461.0,0.0))
  RCONST(212) = ((7.265e-13))
  RCONST(213) = ((2.085e-11))
  RCONST(214) = ((2.20e-10))
  RCONST(215) = ((2.20e-10))
  RCONST(216) = ((2.20e-10))
  RCONST(217) = ((2.20e-10))
  RCONST(218) = ((2.20e-10))
  RCONST(219) = ((2.20e-10))
  RCONST(220) = ((7.00e-7))
  RCONST(221) = ((2.20e-10))
  RCONST(222) = ((2.20e-10))
  RCONST(223) = ((2.20e-10))
  RCONST(224) = ((2.20e-10))
  RCONST(225) = ((7.00e-7))
  RCONST(226) = ((7.00e-7))
  RCONST(227) = ((7.00e-7))
  RCONST(228) = ((7.00e-7))
  RCONST(229) = ((7.00e-7))
  RCONST(230) = ((7.00e-7))
  RCONST(231) = ((7.00e-7))
  RCONST(232) = ((7.00e-7))
  RCONST(233) = ((7.00e-7))
  RCONST(234) = ((7.00e-7))
  RCONST(235) = ((7.00e-7))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE saprc2006_Global

  RCONST(1) = (1.0*SUN)
  RCONST(15) = (1.0*SUN)
  RCONST(16) = (1.0*SUN)
  RCONST(17) = (1.0*SUN)
  RCONST(18) = (1.0*SUN)
  RCONST(22) = (1.0*SUN)
  RCONST(23) = (1.0*SUN)
  RCONST(28) = (1.0*SUN)
  RCONST(34) = (1.0*SUN)
  RCONST(41) = (1.0*SUN)
  RCONST(123) = (1.0*SUN)
  RCONST(124) = (1.0*SUN)
  RCONST(131) = (1.0*SUN)
  RCONST(134) = (1.0*SUN)
  RCONST(137) = (1.0*SUN)
  RCONST(139) = (1.50e-1*SUN)
  RCONST(143) = (1.0*SUN)
  RCONST(145) = (1.0*SUN)
  RCONST(146) = (1.0*SUN)
  RCONST(147) = (6.00e-3*SUN)
  RCONST(150) = (1.0*SUN)
  RCONST(153) = (1.0*SUN)
  RCONST(160) = (5.00e-2*SUN)
  RCONST(166) = (4.10e-3*SUN)
  RCONST(170) = (2.10e-3*SUN)
  RCONST(174) = (4.10e-3*SUN)
  RCONST(176) = (2.00e-2*SUN)
  RCONST(178) = (1.0*SUN)
  RCONST(182) = (3.65e-1*SUN)
  RCONST(184) = (7.28*SUN)
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE saprc2006_Rates

