! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc2006_Initialize.f90
! Time                 : Tue Jul 14 14:49:18 2015
! Working directory    : /home/mahesh/Software/kpp-2.2.3/tmp/saprc
! Equation file        : saprc2006.kpp
! Output root filename : saprc2006
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc2006_Initialize

  USE saprc2006_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE saprc2006_Global

  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 2.447600e+13_dp

  x = (0.0E0)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (0.0E0)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

  VAR(13) = (6.77E-4)*CFACTOR
  VAR(14) = (1.16E-3)*CFACTOR
  VAR(15) = (3.92E-4)*CFACTOR
  VAR(20) = (5.E-2)*CFACTOR
  VAR(32) = (1.E-3)*CFACTOR
  VAR(33) = (4.69E-2)*CFACTOR
  VAR(35) = (3.06E-2)*CFACTOR
  VAR(36) = (8.74E-3)*CFACTOR
  VAR(41) = (5.89E-3)*CFACTOR
  VAR(42) = (4.17E-2)*CFACTOR
  VAR(43) = (1.18E-2)*CFACTOR
  VAR(46) = (5.60E-4)*CFACTOR
  VAR(49) = (7.51E-5)*CFACTOR
  VAR(52) = (6.06E-4)*CFACTOR
  VAR(54) = (8.37E-5)*CFACTOR
  VAR(55) = (5.07E-3)*CFACTOR
  VAR(57) = (1.89E-2)*CFACTOR
  VAR(59) = (1.21E-4)*CFACTOR
  VAR(61) = (4.33E-4)*CFACTOR
  VAR(63) = (8.20E-4)*CFACTOR
  VAR(64) = (1.30E-3)*CFACTOR
  VAR(65) = (1.04E-2)*CFACTOR
  VAR(66) = (8.93E-5)*CFACTOR
  VAR(67) = (7.97E-3)*CFACTOR
  VAR(69) = (2.32E-3)*CFACTOR
  VAR(70) = (1.12E-2)*CFACTOR
  VAR(73) = (1.72E-3)*CFACTOR
  VAR(74) = (3.26E-3)*CFACTOR
  VAR(75) = (1.93E-3)*CFACTOR
  VAR(81) = (1.0E-1)*CFACTOR
  VAR(85) = (5.0E-2)*CFACTOR
  FIX(1) = (1.0E6)*CFACTOR
  FIX(2) = (2.09E+5)*CFACTOR
  FIX(3) = (2.0E+04)*CFACTOR
  FIX(5) = (0.07E0)*CFACTOR
! constant rate coefficients
! END constant rate coefficients

! INLINED initializations

	TSTART = 0.0D0
	TEND = TSTART + 2*24*3600.0D0 ! 2160.0D0*60.0D0
	DT = 3600.D0
        TEMP = 300.0D0

! End INLINED initializations

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE saprc2006_Initialize

