! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : small_f90_HessianSP.f90
! Time                 : Mon Jul 13 09:49:49 2015
! Working directory    : /home/mahesh/Software/kpp-2.2.3/tmp/small_f90
! Equation file        : small_f90.kpp
! Output root filename : small_f90
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE small_f90_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(10) :: IHESS_I = (/ &
       1,  2,  2,  3,  3,  3,  4,  4,  5,  5 /)

  INTEGER, PARAMETER, DIMENSION(10) :: IHESS_J = (/ &
       1,  2,  2,  1,  2,  3,  2,  3,  2,  3 /)

  INTEGER, PARAMETER, DIMENSION(10) :: IHESS_K = (/ &
       3,  3,  5,  3,  3,  4,  5,  4,  5,  4 /)


END MODULE small_f90_HessianSP

