C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.10 (r5498) - 20 Jan 2015 09:48
C
C  Differentiation of lift_wall in forward (tangent) mode:
C   variations   of useful results: lift
C   with respect to varying inputs: lift q x1 x2
C   RW status of diff variables: lift:in-out q:in x1:in x2:in
C
C
C
C
C
      SUBROUTINE LIFT_WALL_DX(x1, x1d, x2, x2d, q, qd, lift, liftd)
      IMPLICIT NONE
      REAL*8 gam, gm1, cfl, eps, mach, alpha
C
      COMMON /constants/ gam, gm1, cfl, eps, mach, alpha
C
C
C
      REAL*8 x1(2), x2(2), q(4), lift, dx, ri, u, v, p
      REAL*8 x1d(2), x2d(2), qd(4), liftd, dxd, rid, pd
C
C
      dxd = x1d(1) - x2d(1)
      dx = x1(1) - x2(1)
C
      rid = -(qd(1)/q(1)**2)
      ri = 1.d0/q(1)
      u = ri*q(2)
      v = ri*q(3)
      pd = gm1*(qd(4)-0.5d0*(rid*(q(2)**2+q(3)**2)+ri*(2*q(2)*qd(2)+2*q(
     +  3)*qd(3))))
      p = gm1*(q(4)-0.5d0*ri*(q(2)**2+q(3)**2))
C
      liftd = liftd + pd*dx + p*dxd
      lift = lift + p*dx
C
      RETURN
      END
