! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc2006_LinearAlgebra.f90
! Time                 : Tue Jul 14 14:49:18 2015
! Working directory    : /home/mahesh/Software/kpp-2.2.3/tmp/saprc
! Equation file        : saprc2006.kpp
! Output root filename : saprc2006
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc2006_LinearAlgebra

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER        :: IER
      DOUBLE COMPLEX :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=dp)  :: b = 0.0
      INTEGER        :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER       :: IER
      REAL(kind=dp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO) 
      REAL(kind=dp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER  :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER       :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO  
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO
      
END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE saprc2006_Parameters
  USE saprc2006_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprc2006_Parameters
!  USE saprc2006_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER) 
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER) 
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO 
!      
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprc2006_Parameters
!  USE saprc2006_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1 
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO  
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0) 
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!      
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE saprc2006_Parameters
!  USE saprc2006_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!      
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE 
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=dp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=dp) :: t, dmax, da, TMP(3)
!      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!      
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF  
!!      END IF  
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!      
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!      
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!      
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE 
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=dp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=dp) :: TMP
!      
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!         
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!      
!      
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!   
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(34) = X(34)-JVS(117)*X(33)
  X(44) = X(44)-JVS(151)*X(36)-JVS(152)*X(43)
  X(45) = X(45)-JVS(155)*X(36)-JVS(156)*X(43)
  X(46) = X(46)-JVS(159)*X(36)-JVS(160)*X(43)
  X(48) = X(48)-JVS(167)*X(36)-JVS(168)*X(43)
  X(49) = X(49)-JVS(172)*X(36)-JVS(173)*X(43)
  X(51) = X(51)-JVS(184)*X(40)
  X(52) = X(52)-JVS(190)*X(43)
  X(53) = X(53)-JVS(196)*X(42)-JVS(197)*X(44)-JVS(198)*X(45)-JVS(199)*X(47)-JVS(200)*X(48)
  X(54) = X(54)-JVS(220)*X(36)-JVS(221)*X(43)-JVS(222)*X(44)-JVS(223)*X(45)-JVS(224)*X(46)
  X(55) = X(55)-JVS(232)*X(29)-JVS(233)*X(33)-JVS(234)*X(34)-JVS(235)*X(35)-JVS(236)*X(42)
  X(56) = X(56)-JVS(246)*X(31)-JVS(247)*X(46)-JVS(248)*X(49)-JVS(249)*X(51)-JVS(250)*X(52)-JVS(251)*X(54)
  X(59) = X(59)-JVS(277)*X(36)-JVS(278)*X(43)-JVS(279)*X(44)-JVS(280)*X(45)-JVS(281)*X(47)-JVS(282)*X(48)-JVS(283)*X(52)&
            &-JVS(284)*X(57)
  X(60) = X(60)-JVS(294)*X(46)-JVS(295)*X(52)
  X(62) = X(62)-JVS(311)*X(33)-JVS(312)*X(35)-JVS(313)*X(42)-JVS(314)*X(44)-JVS(315)*X(45)-JVS(316)*X(55)-JVS(317)*X(61)
  X(64) = X(64)-JVS(345)*X(61)
  X(66) = X(66)-JVS(357)*X(61)
  X(68) = X(68)-JVS(369)*X(61)-JVS(370)*X(67)
  X(69) = X(69)-JVS(376)*X(22)-JVS(377)*X(30)-JVS(378)*X(33)-JVS(379)*X(35)-JVS(380)*X(42)-JVS(381)*X(57)-JVS(382)*X(58)&
            &-JVS(383)*X(65)-JVS(384)*X(66)-JVS(385)*X(67)
  X(70) = X(70)-JVS(400)*X(30)-JVS(401)*X(33)-JVS(402)*X(35)-JVS(403)*X(38)-JVS(404)*X(39)-JVS(405)*X(41)-JVS(406)*X(42)&
            &-JVS(407)*X(47)-JVS(408)*X(55)-JVS(409)*X(57)-JVS(410)*X(58)-JVS(411)*X(59)-JVS(412)*X(60)-JVS(413)*X(61)&
            &-JVS(414)*X(63)-JVS(415)*X(64)-JVS(416)*X(65)-JVS(417)*X(66)-JVS(418)*X(67)-JVS(419)*X(68)
  X(71) = X(71)-JVS(438)*X(34)-JVS(439)*X(63)-JVS(440)*X(65)-JVS(441)*X(66)-JVS(442)*X(67)
  X(72) = X(72)-JVS(451)*X(21)-JVS(452)*X(57)-JVS(453)*X(58)-JVS(454)*X(61)-JVS(455)*X(63)-JVS(456)*X(64)-JVS(457)*X(65)&
            &-JVS(458)*X(67)-JVS(459)*X(68)
  X(73) = X(73)-JVS(466)*X(29)-JVS(467)*X(33)-JVS(468)*X(35)-JVS(469)*X(42)-JVS(470)*X(44)-JVS(471)*X(45)-JVS(472)*X(48)&
            &-JVS(473)*X(50)-JVS(474)*X(57)-JVS(475)*X(58)-JVS(476)*X(63)-JVS(477)*X(64)-JVS(478)*X(65)-JVS(479)*X(66)&
            &-JVS(480)*X(67)-JVS(481)*X(68)-JVS(482)*X(71)-JVS(483)*X(72)
  X(74) = X(74)-JVS(495)*X(33)-JVS(496)*X(35)-JVS(497)*X(42)-JVS(498)*X(58)-JVS(499)*X(64)-JVS(500)*X(65)-JVS(501)*X(66)&
            &-JVS(502)*X(67)-JVS(503)*X(68)-JVS(504)*X(71)-JVS(505)*X(72)
  X(75) = X(75)-JVS(516)*X(35)-JVS(517)*X(42)-JVS(518)*X(43)-JVS(519)*X(61)-JVS(520)*X(63)-JVS(521)*X(65)-JVS(522)*X(66)&
            &-JVS(523)*X(67)-JVS(524)*X(68)-JVS(525)*X(71)-JVS(526)*X(72)
  X(76) = X(76)-JVS(539)*X(47)-JVS(540)*X(48)-JVS(541)*X(57)-JVS(542)*X(58)-JVS(543)*X(61)-JVS(544)*X(63)-JVS(545)*X(64)&
            &-JVS(546)*X(65)-JVS(547)*X(66)-JVS(548)*X(67)-JVS(549)*X(68)-JVS(550)*X(72)
  X(77) = X(77)-JVS(561)*X(26)-JVS(562)*X(49)-JVS(563)*X(67)-JVS(564)*X(72)-JVS(565)*X(76)
  X(78) = X(78)-JVS(578)*X(20)-JVS(579)*X(28)-JVS(580)*X(30)-JVS(581)*X(32)-JVS(582)*X(36)-JVS(583)*X(37)-JVS(584)*X(38)&
            &-JVS(585)*X(39)-JVS(586)*X(40)-JVS(587)*X(41)-JVS(588)*X(43)-JVS(589)*X(44)-JVS(590)*X(45)-JVS(591)*X(47)&
            &-JVS(592)*X(48)-JVS(593)*X(50)-JVS(594)*X(51)-JVS(595)*X(53)-JVS(596)*X(54)-JVS(597)*X(57)-JVS(598)*X(58)&
            &-JVS(599)*X(59)-JVS(600)*X(60)-JVS(601)*X(61)-JVS(602)*X(63)-JVS(603)*X(64)-JVS(604)*X(65)-JVS(605)*X(66)&
            &-JVS(606)*X(67)-JVS(607)*X(68)-JVS(608)*X(69)-JVS(609)*X(70)-JVS(610)*X(71)-JVS(611)*X(72)-JVS(612)*X(73)&
            &-JVS(613)*X(74)-JVS(614)*X(75)-JVS(615)*X(76)-JVS(616)*X(77)
  X(79) = X(79)-JVS(628)*X(20)-JVS(629)*X(21)-JVS(630)*X(22)-JVS(631)*X(28)-JVS(632)*X(29)-JVS(633)*X(30)-JVS(634)*X(32)&
            &-JVS(635)*X(33)-JVS(636)*X(35)-JVS(637)*X(36)-JVS(638)*X(37)-JVS(639)*X(38)-JVS(640)*X(41)-JVS(641)*X(42)&
            &-JVS(642)*X(43)-JVS(643)*X(44)-JVS(644)*X(45)-JVS(645)*X(46)-JVS(646)*X(47)-JVS(647)*X(48)-JVS(648)*X(49)&
            &-JVS(649)*X(50)-JVS(650)*X(52)-JVS(651)*X(53)-JVS(652)*X(54)-JVS(653)*X(55)-JVS(654)*X(56)-JVS(655)*X(57)&
            &-JVS(656)*X(58)-JVS(657)*X(59)-JVS(658)*X(60)-JVS(659)*X(61)-JVS(660)*X(63)-JVS(661)*X(64)-JVS(662)*X(65)&
            &-JVS(663)*X(66)-JVS(664)*X(67)-JVS(665)*X(68)-JVS(666)*X(69)-JVS(667)*X(70)-JVS(668)*X(71)-JVS(669)*X(72)&
            &-JVS(670)*X(73)-JVS(671)*X(74)-JVS(672)*X(75)-JVS(673)*X(76)-JVS(674)*X(77)-JVS(675)*X(78)
  X(80) = X(80)-JVS(686)*X(27)-JVS(687)*X(61)-JVS(688)*X(64)-JVS(689)*X(66)-JVS(690)*X(67)-JVS(691)*X(68)-JVS(692)*X(72)&
            &-JVS(693)*X(76)-JVS(694)*X(77)-JVS(695)*X(78)-JVS(696)*X(79)
  X(81) = X(81)-JVS(706)*X(32)-JVS(707)*X(39)-JVS(708)*X(62)-JVS(709)*X(63)-JVS(710)*X(65)-JVS(711)*X(67)-JVS(712)*X(68)&
            &-JVS(713)*X(70)-JVS(714)*X(71)-JVS(715)*X(72)-JVS(716)*X(74)-JVS(717)*X(75)-JVS(718)*X(76)-JVS(719)*X(77)&
            &-JVS(720)*X(78)-JVS(721)*X(79)-JVS(722)*X(80)
  X(82) = X(82)-JVS(731)*X(31)-JVS(732)*X(37)-JVS(733)*X(46)-JVS(734)*X(49)-JVS(735)*X(51)-JVS(736)*X(52)-JVS(737)*X(54)&
            &-JVS(738)*X(56)-JVS(739)*X(57)-JVS(740)*X(58)-JVS(741)*X(59)-JVS(742)*X(60)-JVS(743)*X(61)-JVS(744)*X(62)&
            &-JVS(745)*X(63)-JVS(746)*X(64)-JVS(747)*X(65)-JVS(748)*X(66)-JVS(749)*X(67)-JVS(750)*X(68)-JVS(751)*X(69)&
            &-JVS(752)*X(70)-JVS(753)*X(71)-JVS(754)*X(72)-JVS(755)*X(73)-JVS(756)*X(74)-JVS(757)*X(75)-JVS(758)*X(76)&
            &-JVS(759)*X(77)-JVS(760)*X(78)-JVS(761)*X(79)-JVS(762)*X(80)-JVS(763)*X(81)
  X(83) = X(83)-JVS(771)*X(34)-JVS(772)*X(38)-JVS(773)*X(42)-JVS(774)*X(55)-JVS(775)*X(57)-JVS(776)*X(58)-JVS(777)*X(61)&
            &-JVS(778)*X(63)-JVS(779)*X(65)-JVS(780)*X(67)-JVS(781)*X(68)-JVS(782)*X(69)-JVS(783)*X(71)-JVS(784)*X(72)&
            &-JVS(785)*X(73)-JVS(786)*X(74)-JVS(787)*X(75)-JVS(788)*X(76)-JVS(789)*X(77)-JVS(790)*X(78)-JVS(791)*X(79)&
            &-JVS(792)*X(80)-JVS(793)*X(81)-JVS(794)*X(82)
  X(84) = X(84)-JVS(801)*X(23)-JVS(802)*X(24)-JVS(803)*X(36)-JVS(804)*X(42)-JVS(805)*X(44)-JVS(806)*X(45)-JVS(807)*X(54)&
            &-JVS(808)*X(55)-JVS(809)*X(63)-JVS(810)*X(64)-JVS(811)*X(65)-JVS(812)*X(66)-JVS(813)*X(67)-JVS(814)*X(68)&
            &-JVS(815)*X(69)-JVS(816)*X(71)-JVS(817)*X(72)-JVS(818)*X(73)-JVS(819)*X(74)-JVS(820)*X(75)-JVS(821)*X(76)&
            &-JVS(822)*X(77)-JVS(823)*X(78)-JVS(824)*X(79)-JVS(825)*X(80)-JVS(826)*X(81)-JVS(827)*X(82)-JVS(828)*X(83)
  X(85) = X(85)-JVS(834)*X(24)-JVS(835)*X(25)-JVS(836)*X(26)-JVS(837)*X(27)-JVS(838)*X(31)-JVS(839)*X(32)-JVS(840)*X(34)&
            &-JVS(841)*X(37)-JVS(842)*X(39)-JVS(843)*X(40)-JVS(844)*X(51)-JVS(845)*X(56)-JVS(846)*X(59)-JVS(847)*X(60)&
            &-JVS(848)*X(61)-JVS(849)*X(62)-JVS(850)*X(63)-JVS(851)*X(64)-JVS(852)*X(65)-JVS(853)*X(66)-JVS(854)*X(67)&
            &-JVS(855)*X(68)-JVS(856)*X(69)-JVS(857)*X(70)-JVS(858)*X(71)-JVS(859)*X(72)-JVS(860)*X(73)-JVS(861)*X(74)&
            &-JVS(862)*X(75)-JVS(863)*X(76)-JVS(864)*X(77)-JVS(865)*X(78)-JVS(866)*X(79)-JVS(867)*X(80)-JVS(868)*X(81)&
            &-JVS(869)*X(82)-JVS(870)*X(83)-JVS(871)*X(84)
  X(86) = X(86)-JVS(876)*X(29)-JVS(877)*X(33)-JVS(878)*X(35)-JVS(879)*X(36)-JVS(880)*X(42)-JVS(881)*X(43)-JVS(882)*X(58)&
            &-JVS(883)*X(61)-JVS(884)*X(63)-JVS(885)*X(65)-JVS(886)*X(66)-JVS(887)*X(67)-JVS(888)*X(68)-JVS(889)*X(71)&
            &-JVS(890)*X(72)-JVS(891)*X(73)-JVS(892)*X(74)-JVS(893)*X(75)-JVS(894)*X(76)-JVS(895)*X(77)-JVS(896)*X(78)&
            &-JVS(897)*X(79)-JVS(898)*X(80)-JVS(899)*X(81)-JVS(900)*X(82)-JVS(901)*X(83)-JVS(902)*X(84)-JVS(903)*X(85)
  X(87) = X(87)-JVS(907)*X(22)-JVS(908)*X(29)-JVS(909)*X(30)-JVS(910)*X(33)-JVS(911)*X(35)-JVS(912)*X(36)-JVS(913)*X(42)&
            &-JVS(914)*X(43)-JVS(915)*X(44)-JVS(916)*X(45)-JVS(917)*X(46)-JVS(918)*X(47)-JVS(919)*X(48)-JVS(920)*X(50)&
            &-JVS(921)*X(52)-JVS(922)*X(57)-JVS(923)*X(58)-JVS(924)*X(60)-JVS(925)*X(61)-JVS(926)*X(63)-JVS(927)*X(64)&
            &-JVS(928)*X(65)-JVS(929)*X(66)-JVS(930)*X(67)-JVS(931)*X(68)-JVS(932)*X(71)-JVS(933)*X(72)-JVS(934)*X(73)&
            &-JVS(935)*X(74)-JVS(936)*X(75)-JVS(937)*X(76)-JVS(938)*X(77)-JVS(939)*X(78)-JVS(940)*X(79)-JVS(941)*X(80)&
            &-JVS(942)*X(81)-JVS(943)*X(82)-JVS(944)*X(83)-JVS(945)*X(84)-JVS(946)*X(85)-JVS(947)*X(86)
  X(88) = X(88)-JVS(950)*X(25)-JVS(951)*X(59)-JVS(952)*X(60)-JVS(953)*X(63)-JVS(954)*X(64)-JVS(955)*X(66)-JVS(956)*X(67)&
            &-JVS(957)*X(68)-JVS(958)*X(72)-JVS(959)*X(73)-JVS(960)*X(74)-JVS(961)*X(75)-JVS(962)*X(76)-JVS(963)*X(77)&
            &-JVS(964)*X(78)-JVS(965)*X(79)-JVS(966)*X(80)-JVS(967)*X(81)-JVS(968)*X(82)-JVS(969)*X(83)-JVS(970)*X(84)&
            &-JVS(971)*X(85)-JVS(972)*X(86)-JVS(973)*X(87)
  X(88) = X(88)/JVS(974)
  X(87) = (X(87)-JVS(949)*X(88))/(JVS(948))
  X(86) = (X(86)-JVS(905)*X(87)-JVS(906)*X(88))/(JVS(904))
  X(85) = (X(85)-JVS(873)*X(86)-JVS(874)*X(87)-JVS(875)*X(88))/(JVS(872))
  X(84) = (X(84)-JVS(830)*X(85)-JVS(831)*X(86)-JVS(832)*X(87)-JVS(833)*X(88))/(JVS(829))
  X(83) = (X(83)-JVS(796)*X(84)-JVS(797)*X(85)-JVS(798)*X(86)-JVS(799)*X(87)-JVS(800)*X(88))/(JVS(795))
  X(82) = (X(82)-JVS(765)*X(83)-JVS(766)*X(84)-JVS(767)*X(85)-JVS(768)*X(86)-JVS(769)*X(87)-JVS(770)*X(88))/(JVS(764))
  X(81) = (X(81)-JVS(724)*X(82)-JVS(725)*X(83)-JVS(726)*X(84)-JVS(727)*X(85)-JVS(728)*X(86)-JVS(729)*X(87)-JVS(730)&
            &*X(88))/(JVS(723))
  X(80) = (X(80)-JVS(698)*X(81)-JVS(699)*X(82)-JVS(700)*X(83)-JVS(701)*X(84)-JVS(702)*X(85)-JVS(703)*X(86)-JVS(704)&
            &*X(87)-JVS(705)*X(88))/(JVS(697))
  X(79) = (X(79)-JVS(677)*X(80)-JVS(678)*X(81)-JVS(679)*X(82)-JVS(680)*X(83)-JVS(681)*X(84)-JVS(682)*X(85)-JVS(683)&
            &*X(86)-JVS(684)*X(87)-JVS(685)*X(88))/(JVS(676))
  X(78) = (X(78)-JVS(618)*X(79)-JVS(619)*X(80)-JVS(620)*X(81)-JVS(621)*X(82)-JVS(622)*X(83)-JVS(623)*X(84)-JVS(624)&
            &*X(85)-JVS(625)*X(86)-JVS(626)*X(87)-JVS(627)*X(88))/(JVS(617))
  X(77) = (X(77)-JVS(567)*X(78)-JVS(568)*X(79)-JVS(569)*X(80)-JVS(570)*X(81)-JVS(571)*X(82)-JVS(572)*X(83)-JVS(573)&
            &*X(84)-JVS(574)*X(85)-JVS(575)*X(86)-JVS(576)*X(87)-JVS(577)*X(88))/(JVS(566))
  X(76) = (X(76)-JVS(552)*X(77)-JVS(553)*X(78)-JVS(554)*X(79)-JVS(555)*X(80)-JVS(556)*X(81)-JVS(557)*X(82)-JVS(558)&
            &*X(84)-JVS(559)*X(85)-JVS(560)*X(88))/(JVS(551))
  X(75) = (X(75)-JVS(528)*X(76)-JVS(529)*X(77)-JVS(530)*X(79)-JVS(531)*X(81)-JVS(532)*X(82)-JVS(533)*X(83)-JVS(534)&
            &*X(84)-JVS(535)*X(85)-JVS(536)*X(86)-JVS(537)*X(87)-JVS(538)*X(88))/(JVS(527))
  X(74) = (X(74)-JVS(507)*X(75)-JVS(508)*X(76)-JVS(509)*X(79)-JVS(510)*X(81)-JVS(511)*X(82)-JVS(512)*X(83)-JVS(513)&
            &*X(85)-JVS(514)*X(86)-JVS(515)*X(87))/(JVS(506))
  X(73) = (X(73)-JVS(485)*X(74)-JVS(486)*X(75)-JVS(487)*X(76)-JVS(488)*X(78)-JVS(489)*X(79)-JVS(490)*X(81)-JVS(491)&
            &*X(82)-JVS(492)*X(85)-JVS(493)*X(86)-JVS(494)*X(87))/(JVS(484))
  X(72) = (X(72)-JVS(461)*X(76)-JVS(462)*X(79)-JVS(463)*X(81)-JVS(464)*X(82)-JVS(465)*X(85))/(JVS(460))
  X(71) = (X(71)-JVS(444)*X(72)-JVS(445)*X(76)-JVS(446)*X(79)-JVS(447)*X(81)-JVS(448)*X(82)-JVS(449)*X(85)-JVS(450)&
            &*X(86))/(JVS(443))
  X(70) = (X(70)-JVS(421)*X(71)-JVS(422)*X(72)-JVS(423)*X(74)-JVS(424)*X(75)-JVS(425)*X(76)-JVS(426)*X(77)-JVS(427)&
            &*X(78)-JVS(428)*X(79)-JVS(429)*X(80)-JVS(430)*X(81)-JVS(431)*X(82)-JVS(432)*X(83)-JVS(433)*X(84)-JVS(434)*X(85)&
            &-JVS(435)*X(86)-JVS(436)*X(87)-JVS(437)*X(88))/(JVS(420))
  X(69) = (X(69)-JVS(387)*X(71)-JVS(388)*X(72)-JVS(389)*X(73)-JVS(390)*X(74)-JVS(391)*X(75)-JVS(392)*X(76)-JVS(393)&
            &*X(77)-JVS(394)*X(79)-JVS(395)*X(80)-JVS(396)*X(81)-JVS(397)*X(82)-JVS(398)*X(84)-JVS(399)*X(88))/(JVS(386))
  X(68) = (X(68)-JVS(372)*X(72)-JVS(373)*X(76)-JVS(374)*X(79)-JVS(375)*X(82))/(JVS(371))
  X(67) = (X(67)-JVS(365)*X(72)-JVS(366)*X(76)-JVS(367)*X(79)-JVS(368)*X(82))/(JVS(364))
  X(66) = (X(66)-JVS(359)*X(67)-JVS(360)*X(72)-JVS(361)*X(76)-JVS(362)*X(79)-JVS(363)*X(82))/(JVS(358))
  X(65) = (X(65)-JVS(353)*X(72)-JVS(354)*X(76)-JVS(355)*X(79)-JVS(356)*X(82))/(JVS(352))
  X(64) = (X(64)-JVS(347)*X(67)-JVS(348)*X(72)-JVS(349)*X(76)-JVS(350)*X(79)-JVS(351)*X(82))/(JVS(346))
  X(63) = (X(63)-JVS(341)*X(72)-JVS(342)*X(76)-JVS(343)*X(79)-JVS(344)*X(82))/(JVS(340))
  X(62) = (X(62)-JVS(319)*X(63)-JVS(320)*X(65)-JVS(321)*X(67)-JVS(322)*X(68)-JVS(323)*X(71)-JVS(324)*X(72)-JVS(325)&
            &*X(74)-JVS(326)*X(75)-JVS(327)*X(76)-JVS(328)*X(77)-JVS(329)*X(78)-JVS(330)*X(79)-JVS(331)*X(80)-JVS(332)*X(81)&
            &-JVS(333)*X(82)-JVS(334)*X(83)-JVS(335)*X(84)-JVS(336)*X(85)-JVS(337)*X(86)-JVS(338)*X(87)-JVS(339)*X(88))&
            &/(JVS(318))
  X(61) = (X(61)-JVS(307)*X(72)-JVS(308)*X(76)-JVS(309)*X(79)-JVS(310)*X(82))/(JVS(306))
  X(60) = (X(60)-JVS(297)*X(77)-JVS(298)*X(78)-JVS(299)*X(79)-JVS(300)*X(80)-JVS(301)*X(81)-JVS(302)*X(82)-JVS(303)&
            &*X(84)-JVS(304)*X(85)-JVS(305)*X(88))/(JVS(296))
  X(59) = (X(59)-JVS(286)*X(60)-JVS(287)*X(63)-JVS(288)*X(66)-JVS(289)*X(72)-JVS(290)*X(76)-JVS(291)*X(78)-JVS(292)&
            &*X(79)-JVS(293)*X(82))/(JVS(285))
  X(58) = (X(58)-JVS(273)*X(72)-JVS(274)*X(76)-JVS(275)*X(79)-JVS(276)*X(82))/(JVS(272))
  X(57) = (X(57)-JVS(268)*X(72)-JVS(269)*X(76)-JVS(270)*X(79)-JVS(271)*X(82))/(JVS(267))
  X(56) = (X(56)-JVS(253)*X(59)-JVS(254)*X(60)-JVS(255)*X(64)-JVS(256)*X(66)-JVS(257)*X(67)-JVS(258)*X(68)-JVS(259)&
            &*X(69)-JVS(260)*X(70)-JVS(261)*X(73)-JVS(262)*X(76)-JVS(263)*X(78)-JVS(264)*X(79)-JVS(265)*X(82)-JVS(266)&
            &*X(85))/(JVS(252))
  X(55) = (X(55)-JVS(238)*X(63)-JVS(239)*X(65)-JVS(240)*X(67)-JVS(241)*X(71)-JVS(242)*X(76)-JVS(243)*X(79)-JVS(244)&
            &*X(82)-JVS(245)*X(85))/(JVS(237))
  X(54) = (X(54)-JVS(226)*X(64)-JVS(227)*X(66)-JVS(228)*X(68)-JVS(229)*X(76)-JVS(230)*X(79)-JVS(231)*X(82))/(JVS(225))
  X(53) = (X(53)-JVS(202)*X(54)-JVS(203)*X(57)-JVS(204)*X(58)-JVS(205)*X(59)-JVS(206)*X(61)-JVS(207)*X(63)-JVS(208)&
            &*X(64)-JVS(209)*X(65)-JVS(210)*X(66)-JVS(211)*X(67)-JVS(212)*X(68)-JVS(213)*X(69)-JVS(214)*X(70)-JVS(215)*X(72)&
            &-JVS(216)*X(73)-JVS(217)*X(76)-JVS(218)*X(79)-JVS(219)*X(82))/(JVS(201))
  X(52) = (X(52)-JVS(192)*X(60)-JVS(193)*X(78)-JVS(194)*X(79)-JVS(195)*X(82))/(JVS(191))
  X(51) = (X(51)-JVS(186)*X(60)-JVS(187)*X(78)-JVS(188)*X(82)-JVS(189)*X(85))/(JVS(185))
  X(50) = (X(50)-JVS(180)*X(78)-JVS(181)*X(79)-JVS(182)*X(86)-JVS(183)*X(87))/(JVS(179))
  X(49) = (X(49)-JVS(175)*X(67)-JVS(176)*X(76)-JVS(177)*X(79)-JVS(178)*X(82))/(JVS(174))
  X(48) = (X(48)-JVS(170)*X(76)-JVS(171)*X(79))/(JVS(169))
  X(47) = (X(47)-JVS(165)*X(76)-JVS(166)*X(79))/(JVS(164))
  X(46) = (X(46)-JVS(162)*X(79)-JVS(163)*X(82))/(JVS(161))
  X(45) = (X(45)-JVS(158)*X(79))/(JVS(157))
  X(44) = (X(44)-JVS(154)*X(79))/(JVS(153))
  X(43) = (X(43)-JVS(150)*X(79))/(JVS(149))
  X(42) = (X(42)-JVS(148)*X(79))/(JVS(147))
  X(41) = (X(41)-JVS(143)*X(79)-JVS(144)*X(83)-JVS(145)*X(86)-JVS(146)*X(87))/(JVS(142))
  X(40) = (X(40)-JVS(138)*X(51)-JVS(139)*X(78)-JVS(140)*X(82)-JVS(141)*X(85))/(JVS(137))
  X(39) = (X(39)-JVS(134)*X(70)-JVS(135)*X(78)-JVS(136)*X(81))/(JVS(133))
  X(38) = (X(38)-JVS(130)*X(78)-JVS(131)*X(79)-JVS(132)*X(83))/(JVS(129))
  X(37) = (X(37)-JVS(126)*X(78)-JVS(127)*X(79)-JVS(128)*X(85))/(JVS(125))
  X(36) = (X(36)-JVS(124)*X(79))/(JVS(123))
  X(35) = (X(35)-JVS(122)*X(79))/(JVS(121))
  X(34) = (X(34)-JVS(119)*X(79)-JVS(120)*X(85))/(JVS(118))
  X(33) = (X(33)-JVS(116)*X(79))/(JVS(115))
  X(32) = (X(32)-JVS(113)*X(79)-JVS(114)*X(81))/(JVS(112))
  X(31) = (X(31)-JVS(110)*X(82)-JVS(111)*X(85))/(JVS(109))
  X(30) = (X(30)-JVS(108)*X(79))/(JVS(107))
  X(29) = (X(29)-JVS(106)*X(79))/(JVS(105))
  X(28) = (X(28)-JVS(103)*X(78)-JVS(104)*X(79))/(JVS(102))
  X(27) = (X(27)-JVS(100)*X(80)-JVS(101)*X(85))/(JVS(99))
  X(26) = (X(26)-JVS(97)*X(77)-JVS(98)*X(85))/(JVS(96))
  X(25) = (X(25)-JVS(94)*X(85)-JVS(95)*X(88))/(JVS(93))
  X(24) = (X(24)-JVS(91)*X(84)-JVS(92)*X(85))/(JVS(90))
  X(23) = (X(23)-JVS(86)*X(36)-JVS(87)*X(63)-JVS(88)*X(76)-JVS(89)*X(79))/(JVS(85))
  X(22) = (X(22)-JVS(84)*X(79))/(JVS(83))
  X(21) = (X(21)-JVS(82)*X(76))/(JVS(81))
  X(20) = (X(20)-JVS(80)*X(79))/(JVS(79))
  X(19) = (X(19)-JVS(71)*X(40)-JVS(72)*X(49)-JVS(73)*X(58)-JVS(74)*X(72)-JVS(75)*X(76)-JVS(76)*X(79)-JVS(77)*X(82)&
            &-JVS(78)*X(85))/(JVS(70))
  X(18) = (X(18)-JVS(66)*X(40)-JVS(67)*X(58)-JVS(68)*X(82)-JVS(69)*X(85))/(JVS(65))
  X(17) = (X(17)-JVS(61)*X(77)-JVS(62)*X(78)-JVS(63)*X(80)-JVS(64)*X(88))/(JVS(60))
  X(16) = (X(16)-JVS(58)*X(78)-JVS(59)*X(84))/(JVS(57))
  X(15) = (X(15)-JVS(44)*X(61)-JVS(45)*X(63)-JVS(46)*X(65)-JVS(47)*X(66)-JVS(48)*X(67)-JVS(49)*X(76)-JVS(50)*X(77)&
            &-JVS(51)*X(78)-JVS(52)*X(80)-JVS(53)*X(83)-JVS(54)*X(86)-JVS(55)*X(87)-JVS(56)*X(88))/(JVS(43))
  X(14) = (X(14)-JVS(34)*X(58)-JVS(35)*X(65)-JVS(36)*X(67)-JVS(37)*X(76)-JVS(38)*X(78)-JVS(39)*X(83)-JVS(40)*X(84)&
            &-JVS(41)*X(86)-JVS(42)*X(87))/(JVS(33))
  X(13) = (X(13)-JVS(19)*X(39)-JVS(20)*X(47)-JVS(21)*X(57)-JVS(22)*X(58)-JVS(23)*X(61)-JVS(24)*X(63)-JVS(25)*X(64)&
            &-JVS(26)*X(65)-JVS(27)*X(66)-JVS(28)*X(67)-JVS(29)*X(68)-JVS(30)*X(76)-JVS(31)*X(79)-JVS(32)*X(81))/(JVS(18))
  X(12) = (X(12)-JVS(15)*X(47)-JVS(16)*X(58)-JVS(17)*X(76))/(JVS(14))
  X(11) = X(11)/JVS(13)
  X(10) = X(10)/JVS(12)
  X(9) = X(9)/JVS(11)
  X(8) = X(8)/JVS(10)
  X(7) = X(7)/JVS(9)
  X(6) = X(6)/JVS(8)
  X(5) = X(5)/JVS(7)
  X(4) = X(4)/JVS(6)
  X(3) = X(3)/JVS(5)
  X(2) = X(2)/JVS(4)
  X(1) = (X(1)-JVS(2)*X(20)-JVS(3)*X(79))/(JVS(1))
      
END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(4)
  XX(3) = X(3)/JVS(5)
  XX(4) = X(4)/JVS(6)
  XX(5) = X(5)/JVS(7)
  XX(6) = X(6)/JVS(8)
  XX(7) = X(7)/JVS(9)
  XX(8) = X(8)/JVS(10)
  XX(9) = X(9)/JVS(11)
  XX(10) = X(10)/JVS(12)
  XX(11) = X(11)/JVS(13)
  XX(12) = X(12)/JVS(14)
  XX(13) = X(13)/JVS(18)
  XX(14) = X(14)/JVS(33)
  XX(15) = X(15)/JVS(43)
  XX(16) = X(16)/JVS(57)
  XX(17) = X(17)/JVS(60)
  XX(18) = X(18)/JVS(65)
  XX(19) = X(19)/JVS(70)
  XX(20) = (X(20)-JVS(2)*XX(1))/(JVS(79))
  XX(21) = X(21)/JVS(81)
  XX(22) = X(22)/JVS(83)
  XX(23) = X(23)/JVS(85)
  XX(24) = X(24)/JVS(90)
  XX(25) = X(25)/JVS(93)
  XX(26) = X(26)/JVS(96)
  XX(27) = X(27)/JVS(99)
  XX(28) = X(28)/JVS(102)
  XX(29) = X(29)/JVS(105)
  XX(30) = X(30)/JVS(107)
  XX(31) = X(31)/JVS(109)
  XX(32) = X(32)/JVS(112)
  XX(33) = X(33)/JVS(115)
  XX(34) = X(34)/JVS(118)
  XX(35) = X(35)/JVS(121)
  XX(36) = (X(36)-JVS(86)*XX(23))/(JVS(123))
  XX(37) = X(37)/JVS(125)
  XX(38) = X(38)/JVS(129)
  XX(39) = (X(39)-JVS(19)*XX(13))/(JVS(133))
  XX(40) = (X(40)-JVS(66)*XX(18)-JVS(71)*XX(19))/(JVS(137))
  XX(41) = X(41)/JVS(142)
  XX(42) = X(42)/JVS(147)
  XX(43) = X(43)/JVS(149)
  XX(44) = X(44)/JVS(153)
  XX(45) = X(45)/JVS(157)
  XX(46) = X(46)/JVS(161)
  XX(47) = (X(47)-JVS(15)*XX(12)-JVS(20)*XX(13))/(JVS(164))
  XX(48) = X(48)/JVS(169)
  XX(49) = (X(49)-JVS(72)*XX(19))/(JVS(174))
  XX(50) = X(50)/JVS(179)
  XX(51) = (X(51)-JVS(138)*XX(40))/(JVS(185))
  XX(52) = X(52)/JVS(191)
  XX(53) = X(53)/JVS(201)
  XX(54) = (X(54)-JVS(202)*XX(53))/(JVS(225))
  XX(55) = X(55)/JVS(237)
  XX(56) = X(56)/JVS(252)
  XX(57) = (X(57)-JVS(21)*XX(13)-JVS(203)*XX(53))/(JVS(267))
  XX(58) = (X(58)-JVS(16)*XX(12)-JVS(22)*XX(13)-JVS(34)*XX(14)-JVS(67)*XX(18)-JVS(73)*XX(19)-JVS(204)*XX(53))/(JVS(272))
  XX(59) = (X(59)-JVS(205)*XX(53)-JVS(253)*XX(56))/(JVS(285))
  XX(60) = (X(60)-JVS(186)*XX(51)-JVS(192)*XX(52)-JVS(254)*XX(56)-JVS(286)*XX(59))/(JVS(296))
  XX(61) = (X(61)-JVS(23)*XX(13)-JVS(44)*XX(15)-JVS(206)*XX(53))/(JVS(306))
  XX(62) = X(62)/JVS(318)
  XX(63) = (X(63)-JVS(24)*XX(13)-JVS(45)*XX(15)-JVS(87)*XX(23)-JVS(207)*XX(53)-JVS(238)*XX(55)-JVS(287)*XX(59)-JVS(319)&
             &*XX(62))/(JVS(340))
  XX(64) = (X(64)-JVS(25)*XX(13)-JVS(208)*XX(53)-JVS(226)*XX(54)-JVS(255)*XX(56))/(JVS(346))
  XX(65) = (X(65)-JVS(26)*XX(13)-JVS(35)*XX(14)-JVS(46)*XX(15)-JVS(209)*XX(53)-JVS(239)*XX(55)-JVS(320)*XX(62))&
             &/(JVS(352))
  XX(66) = (X(66)-JVS(27)*XX(13)-JVS(47)*XX(15)-JVS(210)*XX(53)-JVS(227)*XX(54)-JVS(256)*XX(56)-JVS(288)*XX(59))&
             &/(JVS(358))
  XX(67) = (X(67)-JVS(28)*XX(13)-JVS(36)*XX(14)-JVS(48)*XX(15)-JVS(175)*XX(49)-JVS(211)*XX(53)-JVS(240)*XX(55)-JVS(257)&
             &*XX(56)-JVS(321)*XX(62)-JVS(347)*XX(64)-JVS(359)*XX(66))/(JVS(364))
  XX(68) = (X(68)-JVS(29)*XX(13)-JVS(212)*XX(53)-JVS(228)*XX(54)-JVS(258)*XX(56)-JVS(322)*XX(62))/(JVS(371))
  XX(69) = (X(69)-JVS(213)*XX(53)-JVS(259)*XX(56))/(JVS(386))
  XX(70) = (X(70)-JVS(134)*XX(39)-JVS(214)*XX(53)-JVS(260)*XX(56))/(JVS(420))
  XX(71) = (X(71)-JVS(241)*XX(55)-JVS(323)*XX(62)-JVS(387)*XX(69)-JVS(421)*XX(70))/(JVS(443))
  XX(72) = (X(72)-JVS(74)*XX(19)-JVS(215)*XX(53)-JVS(268)*XX(57)-JVS(273)*XX(58)-JVS(289)*XX(59)-JVS(307)*XX(61)&
             &-JVS(324)*XX(62)-JVS(341)*XX(63)-JVS(348)*XX(64)-JVS(353)*XX(65)-JVS(360)*XX(66)-JVS(365)*XX(67)-JVS(372)&
             &*XX(68)-JVS(388)*XX(69)-JVS(422)*XX(70)-JVS(444)*XX(71))/(JVS(460))
  XX(73) = (X(73)-JVS(216)*XX(53)-JVS(261)*XX(56)-JVS(389)*XX(69))/(JVS(484))
  XX(74) = (X(74)-JVS(325)*XX(62)-JVS(390)*XX(69)-JVS(423)*XX(70)-JVS(485)*XX(73))/(JVS(506))
  XX(75) = (X(75)-JVS(326)*XX(62)-JVS(391)*XX(69)-JVS(424)*XX(70)-JVS(486)*XX(73)-JVS(507)*XX(74))/(JVS(527))
  XX(76) = (X(76)-JVS(17)*XX(12)-JVS(30)*XX(13)-JVS(37)*XX(14)-JVS(49)*XX(15)-JVS(75)*XX(19)-JVS(82)*XX(21)-JVS(88)&
             &*XX(23)-JVS(165)*XX(47)-JVS(170)*XX(48)-JVS(176)*XX(49)-JVS(217)*XX(53)-JVS(229)*XX(54)-JVS(242)*XX(55)&
             &-JVS(262)*XX(56)-JVS(269)*XX(57)-JVS(274)*XX(58)-JVS(290)*XX(59)-JVS(308)*XX(61)-JVS(327)*XX(62)-JVS(342)&
             &*XX(63)-JVS(349)*XX(64)-JVS(354)*XX(65)-JVS(361)*XX(66)-JVS(366)*XX(67)-JVS(373)*XX(68)-JVS(392)*XX(69)&
             &-JVS(425)*XX(70)-JVS(445)*XX(71)-JVS(461)*XX(72)-JVS(487)*XX(73)-JVS(508)*XX(74)-JVS(528)*XX(75))/(JVS(551))
  XX(77) = (X(77)-JVS(50)*XX(15)-JVS(61)*XX(17)-JVS(97)*XX(26)-JVS(297)*XX(60)-JVS(328)*XX(62)-JVS(393)*XX(69)-JVS(426)&
             &*XX(70)-JVS(529)*XX(75)-JVS(552)*XX(76))/(JVS(566))
  XX(78) = (X(78)-JVS(38)*XX(14)-JVS(51)*XX(15)-JVS(58)*XX(16)-JVS(62)*XX(17)-JVS(103)*XX(28)-JVS(126)*XX(37)-JVS(130)&
             &*XX(38)-JVS(135)*XX(39)-JVS(139)*XX(40)-JVS(180)*XX(50)-JVS(187)*XX(51)-JVS(193)*XX(52)-JVS(263)*XX(56)&
             &-JVS(291)*XX(59)-JVS(298)*XX(60)-JVS(329)*XX(62)-JVS(427)*XX(70)-JVS(488)*XX(73)-JVS(553)*XX(76)-JVS(567)&
             &*XX(77))/(JVS(617))
  XX(79) = (X(79)-JVS(3)*XX(1)-JVS(31)*XX(13)-JVS(76)*XX(19)-JVS(80)*XX(20)-JVS(84)*XX(22)-JVS(89)*XX(23)-JVS(104)&
             &*XX(28)-JVS(106)*XX(29)-JVS(108)*XX(30)-JVS(113)*XX(32)-JVS(116)*XX(33)-JVS(119)*XX(34)-JVS(122)*XX(35)&
             &-JVS(124)*XX(36)-JVS(127)*XX(37)-JVS(131)*XX(38)-JVS(143)*XX(41)-JVS(148)*XX(42)-JVS(150)*XX(43)-JVS(154)&
             &*XX(44)-JVS(158)*XX(45)-JVS(162)*XX(46)-JVS(166)*XX(47)-JVS(171)*XX(48)-JVS(177)*XX(49)-JVS(181)*XX(50)&
             &-JVS(194)*XX(52)-JVS(218)*XX(53)-JVS(230)*XX(54)-JVS(243)*XX(55)-JVS(264)*XX(56)-JVS(270)*XX(57)-JVS(275)&
             &*XX(58)-JVS(292)*XX(59)-JVS(299)*XX(60)-JVS(309)*XX(61)-JVS(330)*XX(62)-JVS(343)*XX(63)-JVS(350)*XX(64)&
             &-JVS(355)*XX(65)-JVS(362)*XX(66)-JVS(367)*XX(67)-JVS(374)*XX(68)-JVS(394)*XX(69)-JVS(428)*XX(70)-JVS(446)&
             &*XX(71)-JVS(462)*XX(72)-JVS(489)*XX(73)-JVS(509)*XX(74)-JVS(530)*XX(75)-JVS(554)*XX(76)-JVS(568)*XX(77)&
             &-JVS(618)*XX(78))/(JVS(676))
  XX(80) = (X(80)-JVS(52)*XX(15)-JVS(63)*XX(17)-JVS(100)*XX(27)-JVS(300)*XX(60)-JVS(331)*XX(62)-JVS(395)*XX(69)-JVS(429)&
             &*XX(70)-JVS(555)*XX(76)-JVS(569)*XX(77)-JVS(619)*XX(78)-JVS(677)*XX(79))/(JVS(697))
  XX(81) = (X(81)-JVS(32)*XX(13)-JVS(114)*XX(32)-JVS(136)*XX(39)-JVS(301)*XX(60)-JVS(332)*XX(62)-JVS(396)*XX(69)&
             &-JVS(430)*XX(70)-JVS(447)*XX(71)-JVS(463)*XX(72)-JVS(490)*XX(73)-JVS(510)*XX(74)-JVS(531)*XX(75)-JVS(556)&
             &*XX(76)-JVS(570)*XX(77)-JVS(620)*XX(78)-JVS(678)*XX(79)-JVS(698)*XX(80))/(JVS(723))
  XX(82) = (X(82)-JVS(68)*XX(18)-JVS(77)*XX(19)-JVS(110)*XX(31)-JVS(140)*XX(40)-JVS(163)*XX(46)-JVS(178)*XX(49)-JVS(188)&
             &*XX(51)-JVS(195)*XX(52)-JVS(219)*XX(53)-JVS(231)*XX(54)-JVS(244)*XX(55)-JVS(265)*XX(56)-JVS(271)*XX(57)&
             &-JVS(276)*XX(58)-JVS(293)*XX(59)-JVS(302)*XX(60)-JVS(310)*XX(61)-JVS(333)*XX(62)-JVS(344)*XX(63)-JVS(351)&
             &*XX(64)-JVS(356)*XX(65)-JVS(363)*XX(66)-JVS(368)*XX(67)-JVS(375)*XX(68)-JVS(397)*XX(69)-JVS(431)*XX(70)&
             &-JVS(448)*XX(71)-JVS(464)*XX(72)-JVS(491)*XX(73)-JVS(511)*XX(74)-JVS(532)*XX(75)-JVS(557)*XX(76)-JVS(571)&
             &*XX(77)-JVS(621)*XX(78)-JVS(679)*XX(79)-JVS(699)*XX(80)-JVS(724)*XX(81))/(JVS(764))
  XX(83) = (X(83)-JVS(39)*XX(14)-JVS(53)*XX(15)-JVS(132)*XX(38)-JVS(144)*XX(41)-JVS(334)*XX(62)-JVS(432)*XX(70)-JVS(512)&
             &*XX(74)-JVS(533)*XX(75)-JVS(572)*XX(77)-JVS(622)*XX(78)-JVS(680)*XX(79)-JVS(700)*XX(80)-JVS(725)*XX(81)&
             &-JVS(765)*XX(82))/(JVS(795))
  XX(84) = (X(84)-JVS(40)*XX(14)-JVS(59)*XX(16)-JVS(91)*XX(24)-JVS(303)*XX(60)-JVS(335)*XX(62)-JVS(398)*XX(69)-JVS(433)&
             &*XX(70)-JVS(534)*XX(75)-JVS(558)*XX(76)-JVS(573)*XX(77)-JVS(623)*XX(78)-JVS(681)*XX(79)-JVS(701)*XX(80)&
             &-JVS(726)*XX(81)-JVS(766)*XX(82)-JVS(796)*XX(83))/(JVS(829))
  XX(85) = (X(85)-JVS(69)*XX(18)-JVS(78)*XX(19)-JVS(92)*XX(24)-JVS(94)*XX(25)-JVS(98)*XX(26)-JVS(101)*XX(27)-JVS(111)&
             &*XX(31)-JVS(120)*XX(34)-JVS(128)*XX(37)-JVS(141)*XX(40)-JVS(189)*XX(51)-JVS(245)*XX(55)-JVS(266)*XX(56)&
             &-JVS(304)*XX(60)-JVS(336)*XX(62)-JVS(434)*XX(70)-JVS(449)*XX(71)-JVS(465)*XX(72)-JVS(492)*XX(73)-JVS(513)&
             &*XX(74)-JVS(535)*XX(75)-JVS(559)*XX(76)-JVS(574)*XX(77)-JVS(624)*XX(78)-JVS(682)*XX(79)-JVS(702)*XX(80)&
             &-JVS(727)*XX(81)-JVS(767)*XX(82)-JVS(797)*XX(83)-JVS(830)*XX(84))/(JVS(872))
  XX(86) = (X(86)-JVS(41)*XX(14)-JVS(54)*XX(15)-JVS(145)*XX(41)-JVS(182)*XX(50)-JVS(337)*XX(62)-JVS(435)*XX(70)-JVS(450)&
             &*XX(71)-JVS(493)*XX(73)-JVS(514)*XX(74)-JVS(536)*XX(75)-JVS(575)*XX(77)-JVS(625)*XX(78)-JVS(683)*XX(79)&
             &-JVS(703)*XX(80)-JVS(728)*XX(81)-JVS(768)*XX(82)-JVS(798)*XX(83)-JVS(831)*XX(84)-JVS(873)*XX(85))/(JVS(904))
  XX(87) = (X(87)-JVS(42)*XX(14)-JVS(55)*XX(15)-JVS(146)*XX(41)-JVS(183)*XX(50)-JVS(338)*XX(62)-JVS(436)*XX(70)-JVS(494)&
             &*XX(73)-JVS(515)*XX(74)-JVS(537)*XX(75)-JVS(576)*XX(77)-JVS(626)*XX(78)-JVS(684)*XX(79)-JVS(704)*XX(80)&
             &-JVS(729)*XX(81)-JVS(769)*XX(82)-JVS(799)*XX(83)-JVS(832)*XX(84)-JVS(874)*XX(85)-JVS(905)*XX(86))/(JVS(948))
  XX(88) = (X(88)-JVS(56)*XX(15)-JVS(64)*XX(17)-JVS(95)*XX(25)-JVS(305)*XX(60)-JVS(339)*XX(62)-JVS(399)*XX(69)-JVS(437)&
             &*XX(70)-JVS(538)*XX(75)-JVS(560)*XX(76)-JVS(577)*XX(77)-JVS(627)*XX(78)-JVS(685)*XX(79)-JVS(705)*XX(80)&
             &-JVS(730)*XX(81)-JVS(770)*XX(82)-JVS(800)*XX(83)-JVS(833)*XX(84)-JVS(875)*XX(85)-JVS(906)*XX(86)-JVS(949)&
             &*XX(87))/(JVS(974))
  XX(88) = XX(88)
  XX(87) = XX(87)-JVS(973)*XX(88)
  XX(86) = XX(86)-JVS(947)*XX(87)-JVS(972)*XX(88)
  XX(85) = XX(85)-JVS(903)*XX(86)-JVS(946)*XX(87)-JVS(971)*XX(88)
  XX(84) = XX(84)-JVS(871)*XX(85)-JVS(902)*XX(86)-JVS(945)*XX(87)-JVS(970)*XX(88)
  XX(83) = XX(83)-JVS(828)*XX(84)-JVS(870)*XX(85)-JVS(901)*XX(86)-JVS(944)*XX(87)-JVS(969)*XX(88)
  XX(82) = XX(82)-JVS(794)*XX(83)-JVS(827)*XX(84)-JVS(869)*XX(85)-JVS(900)*XX(86)-JVS(943)*XX(87)-JVS(968)*XX(88)
  XX(81) = XX(81)-JVS(763)*XX(82)-JVS(793)*XX(83)-JVS(826)*XX(84)-JVS(868)*XX(85)-JVS(899)*XX(86)-JVS(942)*XX(87)&
             &-JVS(967)*XX(88)
  XX(80) = XX(80)-JVS(722)*XX(81)-JVS(762)*XX(82)-JVS(792)*XX(83)-JVS(825)*XX(84)-JVS(867)*XX(85)-JVS(898)*XX(86)&
             &-JVS(941)*XX(87)-JVS(966)*XX(88)
  XX(79) = XX(79)-JVS(696)*XX(80)-JVS(721)*XX(81)-JVS(761)*XX(82)-JVS(791)*XX(83)-JVS(824)*XX(84)-JVS(866)*XX(85)&
             &-JVS(897)*XX(86)-JVS(940)*XX(87)-JVS(965)*XX(88)
  XX(78) = XX(78)-JVS(675)*XX(79)-JVS(695)*XX(80)-JVS(720)*XX(81)-JVS(760)*XX(82)-JVS(790)*XX(83)-JVS(823)*XX(84)&
             &-JVS(865)*XX(85)-JVS(896)*XX(86)-JVS(939)*XX(87)-JVS(964)*XX(88)
  XX(77) = XX(77)-JVS(616)*XX(78)-JVS(674)*XX(79)-JVS(694)*XX(80)-JVS(719)*XX(81)-JVS(759)*XX(82)-JVS(789)*XX(83)&
             &-JVS(822)*XX(84)-JVS(864)*XX(85)-JVS(895)*XX(86)-JVS(938)*XX(87)-JVS(963)*XX(88)
  XX(76) = XX(76)-JVS(565)*XX(77)-JVS(615)*XX(78)-JVS(673)*XX(79)-JVS(693)*XX(80)-JVS(718)*XX(81)-JVS(758)*XX(82)&
             &-JVS(788)*XX(83)-JVS(821)*XX(84)-JVS(863)*XX(85)-JVS(894)*XX(86)-JVS(937)*XX(87)-JVS(962)*XX(88)
  XX(75) = XX(75)-JVS(614)*XX(78)-JVS(672)*XX(79)-JVS(717)*XX(81)-JVS(757)*XX(82)-JVS(787)*XX(83)-JVS(820)*XX(84)&
             &-JVS(862)*XX(85)-JVS(893)*XX(86)-JVS(936)*XX(87)-JVS(961)*XX(88)
  XX(74) = XX(74)-JVS(613)*XX(78)-JVS(671)*XX(79)-JVS(716)*XX(81)-JVS(756)*XX(82)-JVS(786)*XX(83)-JVS(819)*XX(84)&
             &-JVS(861)*XX(85)-JVS(892)*XX(86)-JVS(935)*XX(87)-JVS(960)*XX(88)
  XX(73) = XX(73)-JVS(612)*XX(78)-JVS(670)*XX(79)-JVS(755)*XX(82)-JVS(785)*XX(83)-JVS(818)*XX(84)-JVS(860)*XX(85)&
             &-JVS(891)*XX(86)-JVS(934)*XX(87)-JVS(959)*XX(88)
  XX(72) = XX(72)-JVS(483)*XX(73)-JVS(505)*XX(74)-JVS(526)*XX(75)-JVS(550)*XX(76)-JVS(564)*XX(77)-JVS(611)*XX(78)&
             &-JVS(669)*XX(79)-JVS(692)*XX(80)-JVS(715)*XX(81)-JVS(754)*XX(82)-JVS(784)*XX(83)-JVS(817)*XX(84)-JVS(859)&
             &*XX(85)-JVS(890)*XX(86)-JVS(933)*XX(87)-JVS(958)*XX(88)
  XX(71) = XX(71)-JVS(482)*XX(73)-JVS(504)*XX(74)-JVS(525)*XX(75)-JVS(610)*XX(78)-JVS(668)*XX(79)-JVS(714)*XX(81)&
             &-JVS(753)*XX(82)-JVS(783)*XX(83)-JVS(816)*XX(84)-JVS(858)*XX(85)-JVS(889)*XX(86)-JVS(932)*XX(87)
  XX(70) = XX(70)-JVS(609)*XX(78)-JVS(667)*XX(79)-JVS(713)*XX(81)-JVS(752)*XX(82)-JVS(857)*XX(85)
  XX(69) = XX(69)-JVS(608)*XX(78)-JVS(666)*XX(79)-JVS(751)*XX(82)-JVS(782)*XX(83)-JVS(815)*XX(84)-JVS(856)*XX(85)
  XX(68) = XX(68)-JVS(419)*XX(70)-JVS(459)*XX(72)-JVS(481)*XX(73)-JVS(503)*XX(74)-JVS(524)*XX(75)-JVS(549)*XX(76)&
             &-JVS(607)*XX(78)-JVS(665)*XX(79)-JVS(691)*XX(80)-JVS(712)*XX(81)-JVS(750)*XX(82)-JVS(781)*XX(83)-JVS(814)&
             &*XX(84)-JVS(855)*XX(85)-JVS(888)*XX(86)-JVS(931)*XX(87)-JVS(957)*XX(88)
  XX(67) = XX(67)-JVS(370)*XX(68)-JVS(385)*XX(69)-JVS(418)*XX(70)-JVS(442)*XX(71)-JVS(458)*XX(72)-JVS(480)*XX(73)&
             &-JVS(502)*XX(74)-JVS(523)*XX(75)-JVS(548)*XX(76)-JVS(563)*XX(77)-JVS(606)*XX(78)-JVS(664)*XX(79)-JVS(690)&
             &*XX(80)-JVS(711)*XX(81)-JVS(749)*XX(82)-JVS(780)*XX(83)-JVS(813)*XX(84)-JVS(854)*XX(85)-JVS(887)*XX(86)&
             &-JVS(930)*XX(87)-JVS(956)*XX(88)
  XX(66) = XX(66)-JVS(384)*XX(69)-JVS(417)*XX(70)-JVS(441)*XX(71)-JVS(479)*XX(73)-JVS(501)*XX(74)-JVS(522)*XX(75)&
             &-JVS(547)*XX(76)-JVS(605)*XX(78)-JVS(663)*XX(79)-JVS(689)*XX(80)-JVS(748)*XX(82)-JVS(812)*XX(84)-JVS(853)&
             &*XX(85)-JVS(886)*XX(86)-JVS(929)*XX(87)-JVS(955)*XX(88)
  XX(65) = XX(65)-JVS(383)*XX(69)-JVS(416)*XX(70)-JVS(440)*XX(71)-JVS(457)*XX(72)-JVS(478)*XX(73)-JVS(500)*XX(74)&
             &-JVS(521)*XX(75)-JVS(546)*XX(76)-JVS(604)*XX(78)-JVS(662)*XX(79)-JVS(710)*XX(81)-JVS(747)*XX(82)-JVS(779)&
             &*XX(83)-JVS(811)*XX(84)-JVS(852)*XX(85)-JVS(885)*XX(86)-JVS(928)*XX(87)
  XX(64) = XX(64)-JVS(415)*XX(70)-JVS(456)*XX(72)-JVS(477)*XX(73)-JVS(499)*XX(74)-JVS(545)*XX(76)-JVS(603)*XX(78)&
             &-JVS(661)*XX(79)-JVS(688)*XX(80)-JVS(746)*XX(82)-JVS(810)*XX(84)-JVS(851)*XX(85)-JVS(927)*XX(87)-JVS(954)&
             &*XX(88)
  XX(63) = XX(63)-JVS(414)*XX(70)-JVS(439)*XX(71)-JVS(455)*XX(72)-JVS(476)*XX(73)-JVS(520)*XX(75)-JVS(544)*XX(76)&
             &-JVS(602)*XX(78)-JVS(660)*XX(79)-JVS(709)*XX(81)-JVS(745)*XX(82)-JVS(778)*XX(83)-JVS(809)*XX(84)-JVS(850)&
             &*XX(85)-JVS(884)*XX(86)-JVS(926)*XX(87)-JVS(953)*XX(88)
  XX(62) = XX(62)-JVS(708)*XX(81)-JVS(744)*XX(82)-JVS(849)*XX(85)
  XX(61) = XX(61)-JVS(317)*XX(62)-JVS(345)*XX(64)-JVS(357)*XX(66)-JVS(369)*XX(68)-JVS(413)*XX(70)-JVS(454)*XX(72)&
             &-JVS(519)*XX(75)-JVS(543)*XX(76)-JVS(601)*XX(78)-JVS(659)*XX(79)-JVS(687)*XX(80)-JVS(743)*XX(82)-JVS(777)&
             &*XX(83)-JVS(848)*XX(85)-JVS(883)*XX(86)-JVS(925)*XX(87)
  XX(60) = XX(60)-JVS(412)*XX(70)-JVS(600)*XX(78)-JVS(658)*XX(79)-JVS(742)*XX(82)-JVS(847)*XX(85)-JVS(924)*XX(87)&
             &-JVS(952)*XX(88)
  XX(59) = XX(59)-JVS(411)*XX(70)-JVS(599)*XX(78)-JVS(657)*XX(79)-JVS(741)*XX(82)-JVS(846)*XX(85)-JVS(951)*XX(88)
  XX(58) = XX(58)-JVS(382)*XX(69)-JVS(410)*XX(70)-JVS(453)*XX(72)-JVS(475)*XX(73)-JVS(498)*XX(74)-JVS(542)*XX(76)&
             &-JVS(598)*XX(78)-JVS(656)*XX(79)-JVS(740)*XX(82)-JVS(776)*XX(83)-JVS(882)*XX(86)-JVS(923)*XX(87)
  XX(57) = XX(57)-JVS(284)*XX(59)-JVS(381)*XX(69)-JVS(409)*XX(70)-JVS(452)*XX(72)-JVS(474)*XX(73)-JVS(541)*XX(76)&
             &-JVS(597)*XX(78)-JVS(655)*XX(79)-JVS(739)*XX(82)-JVS(775)*XX(83)-JVS(922)*XX(87)
  XX(56) = XX(56)-JVS(654)*XX(79)-JVS(738)*XX(82)-JVS(845)*XX(85)
  XX(55) = XX(55)-JVS(316)*XX(62)-JVS(408)*XX(70)-JVS(653)*XX(79)-JVS(774)*XX(83)-JVS(808)*XX(84)
  XX(54) = XX(54)-JVS(251)*XX(56)-JVS(596)*XX(78)-JVS(652)*XX(79)-JVS(737)*XX(82)-JVS(807)*XX(84)
  XX(53) = XX(53)-JVS(595)*XX(78)-JVS(651)*XX(79)
  XX(52) = XX(52)-JVS(250)*XX(56)-JVS(283)*XX(59)-JVS(295)*XX(60)-JVS(650)*XX(79)-JVS(736)*XX(82)-JVS(921)*XX(87)
  XX(51) = XX(51)-JVS(249)*XX(56)-JVS(594)*XX(78)-JVS(735)*XX(82)-JVS(844)*XX(85)
  XX(50) = XX(50)-JVS(473)*XX(73)-JVS(593)*XX(78)-JVS(649)*XX(79)-JVS(920)*XX(87)
  XX(49) = XX(49)-JVS(248)*XX(56)-JVS(562)*XX(77)-JVS(648)*XX(79)-JVS(734)*XX(82)
  XX(48) = XX(48)-JVS(200)*XX(53)-JVS(282)*XX(59)-JVS(472)*XX(73)-JVS(540)*XX(76)-JVS(592)*XX(78)-JVS(647)*XX(79)&
             &-JVS(919)*XX(87)
  XX(47) = XX(47)-JVS(199)*XX(53)-JVS(281)*XX(59)-JVS(407)*XX(70)-JVS(539)*XX(76)-JVS(591)*XX(78)-JVS(646)*XX(79)&
             &-JVS(918)*XX(87)
  XX(46) = XX(46)-JVS(224)*XX(54)-JVS(247)*XX(56)-JVS(294)*XX(60)-JVS(645)*XX(79)-JVS(733)*XX(82)-JVS(917)*XX(87)
  XX(45) = XX(45)-JVS(198)*XX(53)-JVS(223)*XX(54)-JVS(280)*XX(59)-JVS(315)*XX(62)-JVS(471)*XX(73)-JVS(590)*XX(78)&
             &-JVS(644)*XX(79)-JVS(806)*XX(84)-JVS(916)*XX(87)
  XX(44) = XX(44)-JVS(197)*XX(53)-JVS(222)*XX(54)-JVS(279)*XX(59)-JVS(314)*XX(62)-JVS(470)*XX(73)-JVS(589)*XX(78)&
             &-JVS(643)*XX(79)-JVS(805)*XX(84)-JVS(915)*XX(87)
  XX(43) = XX(43)-JVS(152)*XX(44)-JVS(156)*XX(45)-JVS(160)*XX(46)-JVS(168)*XX(48)-JVS(173)*XX(49)-JVS(190)*XX(52)&
             &-JVS(221)*XX(54)-JVS(278)*XX(59)-JVS(518)*XX(75)-JVS(588)*XX(78)-JVS(642)*XX(79)-JVS(881)*XX(86)-JVS(914)&
             &*XX(87)
  XX(42) = XX(42)-JVS(196)*XX(53)-JVS(236)*XX(55)-JVS(313)*XX(62)-JVS(380)*XX(69)-JVS(406)*XX(70)-JVS(469)*XX(73)&
             &-JVS(497)*XX(74)-JVS(517)*XX(75)-JVS(641)*XX(79)-JVS(773)*XX(83)-JVS(804)*XX(84)-JVS(880)*XX(86)-JVS(913)&
             &*XX(87)
  XX(41) = XX(41)-JVS(405)*XX(70)-JVS(587)*XX(78)-JVS(640)*XX(79)
  XX(40) = XX(40)-JVS(184)*XX(51)-JVS(586)*XX(78)-JVS(843)*XX(85)
  XX(39) = XX(39)-JVS(404)*XX(70)-JVS(585)*XX(78)-JVS(707)*XX(81)-JVS(842)*XX(85)
  XX(38) = XX(38)-JVS(403)*XX(70)-JVS(584)*XX(78)-JVS(639)*XX(79)-JVS(772)*XX(83)
  XX(37) = XX(37)-JVS(583)*XX(78)-JVS(638)*XX(79)-JVS(732)*XX(82)-JVS(841)*XX(85)
  XX(36) = XX(36)-JVS(151)*XX(44)-JVS(155)*XX(45)-JVS(159)*XX(46)-JVS(167)*XX(48)-JVS(172)*XX(49)-JVS(220)*XX(54)&
             &-JVS(277)*XX(59)-JVS(582)*XX(78)-JVS(637)*XX(79)-JVS(803)*XX(84)-JVS(879)*XX(86)-JVS(912)*XX(87)
  XX(35) = XX(35)-JVS(235)*XX(55)-JVS(312)*XX(62)-JVS(379)*XX(69)-JVS(402)*XX(70)-JVS(468)*XX(73)-JVS(496)*XX(74)&
             &-JVS(516)*XX(75)-JVS(636)*XX(79)-JVS(878)*XX(86)-JVS(911)*XX(87)
  XX(34) = XX(34)-JVS(234)*XX(55)-JVS(438)*XX(71)-JVS(771)*XX(83)-JVS(840)*XX(85)
  XX(33) = XX(33)-JVS(117)*XX(34)-JVS(233)*XX(55)-JVS(311)*XX(62)-JVS(378)*XX(69)-JVS(401)*XX(70)-JVS(467)*XX(73)&
             &-JVS(495)*XX(74)-JVS(635)*XX(79)-JVS(877)*XX(86)-JVS(910)*XX(87)
  XX(32) = XX(32)-JVS(581)*XX(78)-JVS(634)*XX(79)-JVS(706)*XX(81)-JVS(839)*XX(85)
  XX(31) = XX(31)-JVS(246)*XX(56)-JVS(731)*XX(82)-JVS(838)*XX(85)
  XX(30) = XX(30)-JVS(377)*XX(69)-JVS(400)*XX(70)-JVS(580)*XX(78)-JVS(633)*XX(79)-JVS(909)*XX(87)
  XX(29) = XX(29)-JVS(232)*XX(55)-JVS(466)*XX(73)-JVS(632)*XX(79)-JVS(876)*XX(86)-JVS(908)*XX(87)
  XX(28) = XX(28)-JVS(579)*XX(78)-JVS(631)*XX(79)
  XX(27) = XX(27)-JVS(686)*XX(80)-JVS(837)*XX(85)
  XX(26) = XX(26)-JVS(561)*XX(77)-JVS(836)*XX(85)
  XX(25) = XX(25)-JVS(835)*XX(85)-JVS(950)*XX(88)
  XX(24) = XX(24)-JVS(802)*XX(84)-JVS(834)*XX(85)
  XX(23) = XX(23)-JVS(801)*XX(84)
  XX(22) = XX(22)-JVS(376)*XX(69)-JVS(630)*XX(79)-JVS(907)*XX(87)
  XX(21) = XX(21)-JVS(451)*XX(72)-JVS(629)*XX(79)
  XX(20) = XX(20)-JVS(578)*XX(78)-JVS(628)*XX(79)
  XX(19) = XX(19)
  XX(18) = XX(18)
  XX(17) = XX(17)
  XX(16) = XX(16)
  XX(15) = XX(15)
  XX(14) = XX(14)
  XX(13) = XX(13)
  XX(12) = XX(12)
  XX(11) = XX(11)
  XX(10) = XX(10)
  XX(9) = XX(9)
  XX(8) = XX(8)
  XX(7) = XX(7)
  XX(6) = XX(6)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! BLAS_UTIL - BLAS-LIKE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!--------------------------------------------------------------
!
! BLAS/LAPACK-like subroutines used by the integration algorithms
! It is recommended to replace them by calls to the optimized
!      BLAS/LAPACK library for your machine
!
!  (C) Adrian Sandu, Aug. 2004
!      Virginia Polytechnic Institute and State University
!--------------------------------------------------------------


!--------------------------------------------------------------
      SUBROUTINE WCOPY(N,X,incX,Y,incY)
!--------------------------------------------------------------
!     copies a vector, x, to a vector, y:  y <- x
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL  SCOPY(N,X,1,Y,1)   or   CALL  DCOPY(N,X,1,Y,1)
!--------------------------------------------------------------
!     USE saprc2006_Precision
      
      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N)

      IF (N.LE.0) RETURN

      M = MOD(N,8)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = X(i)
        END DO
        IF( N .LT. 8 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,8
        Y(i) = X(i)
        Y(i + 1) = X(i + 1)
        Y(i + 2) = X(i + 2)
        Y(i + 3) = X(i + 3)
        Y(i + 4) = X(i + 4)
        Y(i + 5) = X(i + 5)
        Y(i + 6) = X(i + 6)
        Y(i + 7) = X(i + 7)
      END DO

      END SUBROUTINE WCOPY


!--------------------------------------------------------------
      SUBROUTINE WAXPY(N,Alpha,X,incX,Y,incY)
!--------------------------------------------------------------
!     constant times a vector plus a vector: y <- y + Alpha*x
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SAXPY(N,Alpha,X,1,Y,1) or  CALL DAXPY(N,Alpha,X,1,Y,1)
!--------------------------------------------------------------

      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N),Alpha
      REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp

      IF (Alpha .EQ. ZERO) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,4)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = Y(i) + Alpha*X(i)
        END DO
        IF( N .LT. 4 ) RETURN
      END IF
      MP1 = M + 1
      DO i = MP1,N,4
        Y(i) = Y(i) + Alpha*X(i)
        Y(i + 1) = Y(i + 1) + Alpha*X(i + 1)
        Y(i + 2) = Y(i + 2) + Alpha*X(i + 2)
        Y(i + 3) = Y(i + 3) + Alpha*X(i + 3)
      END DO
      
      END SUBROUTINE WAXPY



!--------------------------------------------------------------
      SUBROUTINE WSCAL(N,Alpha,X,incX)
!--------------------------------------------------------------
!     constant times a vector: x(1:N) <- Alpha*x(1:N) 
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SSCAL(N,Alpha,X,1) or  CALL DSCAL(N,Alpha,X,1)
!--------------------------------------------------------------

      INTEGER  :: i,incX,M,MP1,N
      REAL(kind=dp)  :: X(N),Alpha
      REAL(kind=dp), PARAMETER  :: ZERO=0.0_dp, ONE=1.0_dp

      IF (Alpha .EQ. ONE) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,5)
      IF( M .NE. 0 ) THEN
        IF (Alpha .EQ. (-ONE)) THEN
          DO i = 1,M
            X(i) = -X(i)
          END DO
        ELSEIF (Alpha .EQ. ZERO) THEN
          DO i = 1,M
            X(i) = ZERO
          END DO
        ELSE
          DO i = 1,M
            X(i) = Alpha*X(i)
          END DO
        END IF
        IF( N .LT. 5 ) RETURN
      END IF
      MP1 = M + 1
      IF (Alpha .EQ. (-ONE)) THEN
        DO i = MP1,N,5
          X(i)     = -X(i)
          X(i + 1) = -X(i + 1)
          X(i + 2) = -X(i + 2)
          X(i + 3) = -X(i + 3)
          X(i + 4) = -X(i + 4)
        END DO
      ELSEIF (Alpha .EQ. ZERO) THEN
        DO i = MP1,N,5
          X(i)     = ZERO
          X(i + 1) = ZERO
          X(i + 2) = ZERO
          X(i + 3) = ZERO
          X(i + 4) = ZERO
        END DO
      ELSE
        DO i = MP1,N,5
          X(i)     = Alpha*X(i)
          X(i + 1) = Alpha*X(i + 1)
          X(i + 2) = Alpha*X(i + 2)
          X(i + 3) = Alpha*X(i + 3)
          X(i + 4) = Alpha*X(i + 4)
        END DO
      END IF

      END SUBROUTINE WSCAL

!--------------------------------------------------------------
      REAL(kind=dp) FUNCTION WLAMCH( C )
!--------------------------------------------------------------
!     returns epsilon machine
!     after LAPACK
!     replace this by the function from the optimized LAPACK implementation:
!          CALL SLAMCH('E') or CALL DLAMCH('E')
!--------------------------------------------------------------
!      USE saprc2006_Precision

      CHARACTER ::  C
      INTEGER    :: i
      REAL(kind=dp), SAVE  ::  Eps
      REAL(kind=dp)  ::  Suma
      REAL(kind=dp), PARAMETER  ::  ONE=1.0_dp, HALF=0.5_dp
      LOGICAL, SAVE   ::  First=.TRUE.
      
      IF (First) THEN
        First = .FALSE.
        Eps = HALF**(16)
        DO i = 17, 80
          Eps = Eps*HALF
          CALL WLAMCH_ADD(ONE,Eps,Suma)
          IF (Suma.LE.ONE) GOTO 10
        END DO
        PRINT*,'ERROR IN WLAMCH. EPS < ',Eps
        RETURN
10      Eps = Eps*2
        i = i-1      
      END IF

      WLAMCH = Eps

      END FUNCTION WLAMCH
     
      SUBROUTINE WLAMCH_ADD( A, B, Suma )
!      USE saprc2006_Precision
      
      REAL(kind=dp) A, B, Suma
      Suma = A + B

      END SUBROUTINE WLAMCH_ADD
!--------------------------------------------------------------


!--------------------------------------------------------------
      SUBROUTINE SET2ZERO(N,Y)
!--------------------------------------------------------------
!     copies zeros into the vector y:  y <- 0
!     after BLAS
!--------------------------------------------------------------
      
      INTEGER ::  i,M,MP1,N
      REAL(kind=dp) ::  Y(N)
      REAL(kind=dp), PARAMETER :: ZERO = 0.0d0

      IF (N.LE.0) RETURN

      M = MOD(N,8)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = ZERO
        END DO
        IF( N .LT. 8 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,8
        Y(i)     = ZERO
        Y(i + 1) = ZERO
        Y(i + 2) = ZERO
        Y(i + 3) = ZERO
        Y(i + 4) = ZERO
        Y(i + 5) = ZERO
        Y(i + 6) = ZERO
        Y(i + 7) = ZERO
      END DO

      END SUBROUTINE SET2ZERO


!--------------------------------------------------------------
      REAL(kind=dp) FUNCTION WDOT (N, DX, incX, DY, incY) 
!--------------------------------------------------------------
!     dot produce: wdot = x(1:N)*y(1:N) 
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SDOT(N,X,1,Y,1) or  CALL DDOT(N,X,1,Y,1)
!--------------------------------------------------------------
!      USE messy_mecca_kpp_Precision
!--------------------------------------------------------------
      IMPLICIT NONE
      INTEGER :: N, incX, incY
      REAL(kind=dp) :: DX(N), DY(N) 

      INTEGER :: i, IX, IY, M, MP1, NS
                                 
      WDOT = 0.0D0 
      IF (N .LE. 0) RETURN 
      IF (incX .EQ. incY) IF (incX-1) 5,20,60 
!                                                                       
!     Code for unequal or nonpositive increments.                       
!                                                                       
    5 IX = 1 
      IY = 1 
      IF (incX .LT. 0) IX = (-N+1)*incX + 1 
      IF (incY .LT. 0) IY = (-N+1)*incY + 1 
      DO i = 1,N 
        WDOT = WDOT + DX(IX)*DY(IY) 
        IX = IX + incX 
        IY = IY + incY 
      END DO 
      RETURN 
!                                                                       
!     Code for both increments equal to 1.                              
!                                                                       
!     Clean-up loop so remaining vector length is a multiple of 5.      
!                                                                       
   20 M = MOD(N,5) 
      IF (M .EQ. 0) GO TO 40 
      DO i = 1,M 
         WDOT = WDOT + DX(i)*DY(i) 
      END DO 
      IF (N .LT. 5) RETURN 
   40 MP1 = M + 1 
      DO i = MP1,N,5 
          WDOT = WDOT + DX(i)*DY(i) + DX(i+1)*DY(i+1) + DX(i+2)*DY(i+2) +  &
                   DX(i+3)*DY(i+3) + DX(i+4)*DY(i+4)                   
      END DO 
      RETURN 
!                                                                       
!     Code for equal, positive, non-unit increments.                    
!                                                                       
   60 NS = N*incX 
      DO i = 1,NS,incX 
        WDOT = WDOT + DX(i)*DY(i) 
      END DO 

      END FUNCTION WDOT                                          


!--------------------------------------------------------------
      SUBROUTINE WADD(N,X,Y,Z)
!--------------------------------------------------------------
!     adds two vectors: z <- x + y
!     BLAS - like
!--------------------------------------------------------------
!     USE saprc2006_Precision
      
      INTEGER :: i, M, MP1, N
      REAL(kind=dp) :: X(N),Y(N),Z(N)

      IF (N.LE.0) RETURN

      M = MOD(N,5)
      IF( M /= 0 ) THEN
         DO i = 1,M
            Z(i) = X(i) + Y(i)
         END DO
         IF( N < 5 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,5
         Z(i)     = X(i)     + Y(i)
         Z(i + 1) = X(i + 1) + Y(i + 1)
         Z(i + 2) = X(i + 2) + Y(i + 2)
         Z(i + 3) = X(i + 3) + Y(i + 3)
         Z(i + 4) = X(i + 4) + Y(i + 4)
      END DO

      END SUBROUTINE WADD
      
      
      
!--------------------------------------------------------------
      SUBROUTINE WGEFA(N,A,Ipvt,info)
!--------------------------------------------------------------
!     WGEFA FACTORS THE MATRIX A (N,N) BY
!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!     LINPACK - LIKE 
!--------------------------------------------------------------
!
      INTEGER       :: N,Ipvt(N),info
      REAL(kind=dp) :: A(N,N)
      REAL(kind=dp) :: t, dmax, da
      INTEGER       :: j,k,l
      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0

      info = 0

size: IF (n > 1) THEN
      
col:  DO k = 1, n-1

!        find l = pivot index
!        l = idamax(n-k+1,A(k,k),1) + k - 1
         l = k; dmax = abs(A(k,k))
         DO j = k+1,n
            da = ABS(A(j,k))
            IF (da > dmax) THEN
              l = j; dmax = da
            END IF
         END DO
         Ipvt(k) = l

!        zero pivot implies this column already triangularized
         IF (ABS(A(l,k)) < TINY(ZERO)) THEN
            info = k
            return
         ELSE   
            IF (l /= k) THEN
               t = A(l,k); A(l,k) = A(k,k); A(k,k) = t
            END IF
            t = -ONE/A(k,k)
            CALL WSCAL(n-k,t,A(k+1,k),1)
            DO j = k+1, n
               t = A(l,j)
               IF (l /= k) THEN
                  A(l,j) = A(k,j); A(k,j) = t
               END IF
               CALL WAXPY(n-k,t,A(k+1,k),1,A(k+1,j),1)
            END DO         
         END IF
         
       END DO col
       
      END IF size
      
      Ipvt(N) = N
      IF (ABS(A(N,N)) == ZERO) info = N
      
      END SUBROUTINE WGEFA


!--------------------------------------------------------------
      SUBROUTINE WGESL(Trans,N,A,Ipvt,b)
!--------------------------------------------------------------
!     WGESL solves the system
!     a * x = b  or  trans(a) * x = b
!     using the factors computed by WGEFA.
!
!     Trans      = 'N'   to solve  A*x = b ,
!                = 'T'   to solve  transpose(A)*x = b
!     LINPACK - LIKE 
!--------------------------------------------------------------

      INTEGER       :: N,Ipvt(N)
      CHARACTER     :: trans
      REAL(kind=dp) :: A(N,N),b(N)
      REAL(kind=dp) :: t
      INTEGER       :: k,kb,l

      
      SELECT CASE (Trans)

      CASE ('n','N')  !  Solve  A * x = b

!        first solve  L*y = b
         IF (n >= 2) THEN
          DO k = 1, n-1
            l = Ipvt(k)
            t = b(l)
            IF (l /= k) THEN
               b(l) = b(k)
               b(k) = t
            END IF
            CALL WAXPY(n-k,t,a(k+1,k),1,b(k+1),1)
          END DO
         END IF
!        now solve  U*x = y
         DO kb = 1, n
            k = n + 1 - kb
            b(k) = b(k)/a(k,k)
            t = -b(k)
            CALL WAXPY(k-1,t,a(1,k),1,b(1),1)
         END DO
      
      CASE ('t','T')  !  Solve transpose(A) * x = b

!        first solve  trans(U)*y = b
         DO k = 1, n
            t = WDOT(k-1,a(1,k),1,b(1),1)
            b(k) = (b(k) - t)/a(k,k)
         END DO
!        now solve trans(L)*x = y
         IF (n >= 2) THEN
         DO kb = 1, n-1
            k = n - kb
            b(k) = b(k) + WDOT(n-k,a(k+1,k),1,b(k+1),1)
            l = Ipvt(k)
            IF (l /= k) THEN
               t = b(l); b(l) = b(k); b(k) = t
            END IF
         END DO
         END IF
   
      END SELECT

      END SUBROUTINE WGESL
! End of BLAS_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE saprc2006_LinearAlgebra

