! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc2006_Parameters.f90
! Time                 : Tue Jul 14 14:49:18 2015
! Working directory    : /home/mahesh/Software/kpp-2.2.3/tmp/saprc
! Equation file        : saprc2006.kpp
! Output root filename : saprc2006
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc2006_Parameters

  USE saprc2006_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 93 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 88 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 81 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 235 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 89 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 893 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 974 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 89 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 236 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 893 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 93 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 4 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_BC = 2 
  INTEGER, PARAMETER :: ind_OC = 3 
  INTEGER, PARAMETER :: ind_SSF = 4 
  INTEGER, PARAMETER :: ind_SSC = 5 
  INTEGER, PARAMETER :: ind_PM10 = 6 
  INTEGER, PARAMETER :: ind_PM25 = 7 
  INTEGER, PARAMETER :: ind_DMS = 8 
  INTEGER, PARAMETER :: ind_DST1 = 9 
  INTEGER, PARAMETER :: ind_DST2 = 10 
  INTEGER, PARAMETER :: ind_DST3 = 11 
  INTEGER, PARAMETER :: ind_CO2 = 12 
  INTEGER, PARAMETER :: ind_HCOOH = 13 
  INTEGER, PARAMETER :: ind_CCO_OH = 14 
  INTEGER, PARAMETER :: ind_RCO_OH = 15 
  INTEGER, PARAMETER :: ind_CCO_OOH = 16 
  INTEGER, PARAMETER :: ind_RCO_OOH = 17 
  INTEGER, PARAMETER :: ind_XN = 18 
  INTEGER, PARAMETER :: ind_XC = 19 
  INTEGER, PARAMETER :: ind_SO2 = 20 
  INTEGER, PARAMETER :: ind_O1D = 21 
  INTEGER, PARAMETER :: ind_C2H6 = 22 
  INTEGER, PARAMETER :: ind_BACL = 23 
  INTEGER, PARAMETER :: ind_PAN = 24 
  INTEGER, PARAMETER :: ind_PAN2 = 25 
  INTEGER, PARAMETER :: ind_PBZN = 26 
  INTEGER, PARAMETER :: ind_MA_PAN = 27 
  INTEGER, PARAMETER :: ind_H2O2 = 28 
  INTEGER, PARAMETER :: ind_C3H8 = 29 
  INTEGER, PARAMETER :: ind_ETOH = 30 
  INTEGER, PARAMETER :: ind_N2O5 = 31 
  INTEGER, PARAMETER :: ind_HONO = 32 
  INTEGER, PARAMETER :: ind_ALK3 = 33 
  INTEGER, PARAMETER :: ind_TBU_O = 34 
  INTEGER, PARAMETER :: ind_ALK5 = 35 
  INTEGER, PARAMETER :: ind_ARO2 = 36 
  INTEGER, PARAMETER :: ind_HNO4 = 37 
  INTEGER, PARAMETER :: ind_COOH = 38 
  INTEGER, PARAMETER :: ind_HOCOO = 39 
  INTEGER, PARAMETER :: ind_BZNO2_O = 40 
  INTEGER, PARAMETER :: ind_MEOH = 41 
  INTEGER, PARAMETER :: ind_ALK4 = 42 
  INTEGER, PARAMETER :: ind_ARO1 = 43 
  INTEGER, PARAMETER :: ind_DCB3 = 44 
  INTEGER, PARAMETER :: ind_DCB2 = 45 
  INTEGER, PARAMETER :: ind_CRES = 46 
  INTEGER, PARAMETER :: ind_C2H2 = 47 
  INTEGER, PARAMETER :: ind_DCB1 = 48 
  INTEGER, PARAMETER :: ind_BALD = 49 
  INTEGER, PARAMETER :: ind_ROOH = 50 
  INTEGER, PARAMETER :: ind_NPHE = 51 
  INTEGER, PARAMETER :: ind_PHEN = 52 
  INTEGER, PARAMETER :: ind_CO = 53 
  INTEGER, PARAMETER :: ind_MGLY = 54 
  INTEGER, PARAMETER :: ind_ACET = 55 
  INTEGER, PARAMETER :: ind_HNO3 = 56 
  INTEGER, PARAMETER :: ind_ETHENE = 57 
  INTEGER, PARAMETER :: ind_C3H6 = 58 
  INTEGER, PARAMETER :: ind_GLY = 59 
  INTEGER, PARAMETER :: ind_BZ_O = 60 
  INTEGER, PARAMETER :: ind_ISOPRENE = 61 
  INTEGER, PARAMETER :: ind_R2O2 = 62 
  INTEGER, PARAMETER :: ind_TERP = 63 
  INTEGER, PARAMETER :: ind_METHACRO = 64 
  INTEGER, PARAMETER :: ind_OLE1 = 65 
  INTEGER, PARAMETER :: ind_ISOPROD = 66 
  INTEGER, PARAMETER :: ind_OLE2 = 67 
  INTEGER, PARAMETER :: ind_MVK = 68 
  INTEGER, PARAMETER :: ind_CCHO = 69 
  INTEGER, PARAMETER :: ind_HCHO = 70 
  INTEGER, PARAMETER :: ind_RNO3 = 71 
  INTEGER, PARAMETER :: ind_O3P = 72 
  INTEGER, PARAMETER :: ind_RCHO = 73 
  INTEGER, PARAMETER :: ind_MEK = 74 
  INTEGER, PARAMETER :: ind_PROD2 = 75 
  INTEGER, PARAMETER :: ind_O3 = 76 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 77 
  INTEGER, PARAMETER :: ind_HO2 = 78 
  INTEGER, PARAMETER :: ind_OH = 79 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 80 
  INTEGER, PARAMETER :: ind_NO = 81 
  INTEGER, PARAMETER :: ind_NO3 = 82 
  INTEGER, PARAMETER :: ind_C_O2 = 83 
  INTEGER, PARAMETER :: ind_CCO_O2 = 84 
  INTEGER, PARAMETER :: ind_NO2 = 85 
  INTEGER, PARAMETER :: ind_RO2_N = 86 
  INTEGER, PARAMETER :: ind_RO2_R = 87 
  INTEGER, PARAMETER :: ind_RCO_O2 = 88 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_AIR = 89 
  INTEGER, PARAMETER :: ind_O2 = 90 
  INTEGER, PARAMETER :: ind_H2O = 91 
  INTEGER, PARAMETER :: ind_H2 = 92 
  INTEGER, PARAMETER :: ind_CH4 = 93 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_AIR = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_H2O = 3 
  INTEGER, PARAMETER :: indf_H2 = 4 
  INTEGER, PARAMETER :: indf_CH4 = 5 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 394 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 1087 

END MODULE saprc2006_Parameters

