C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.10 (r5498) - 20 Jan 2015 09:48
C
C  Differentiation of flux_wall in forward (tangent) mode:
C   variations   of useful results: res
C   with respect to varying inputs: res q
C   RW status of diff variables: res:in-out q:in
C
C
C
C
C
      SUBROUTINE FLUX_WALL_D(x1, x2, q, qd, res, resd)
      IMPLICIT NONE
      REAL*8 gam, gm1, cfl, eps, mach, alpha
C
      COMMON /constants/ gam, gm1, cfl, eps, mach, alpha
C
C
      INTEGER n
C
      REAL*8 x1(2), x2(2), q(4), res(4), dx, dy, ri, u, v, p
      REAL*8 qd(4), resd(4), rid, pd
C
C
      dx = x1(1) - x2(1)
      dy = x1(2) - x2(2)
C
      rid = -(qd(1)/q(1)**2)
      ri = 1.d0/q(1)
      u = ri*q(2)
      v = ri*q(3)
      pd = gm1*(qd(4)-0.5d0*(rid*(q(2)**2+q(3)**2)+ri*(2*q(2)*qd(2)+2*q(
     +  3)*qd(3))))
      p = gm1*(q(4)-0.5d0*ri*(q(2)**2+q(3)**2))
C
      resd(2) = resd(2) - dy*pd
      res(2) = res(2) - p*dy
      resd(3) = resd(3) + dx*pd
      res(3) = res(3) + p*dx
C
      RETURN
      END
