C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.10 (r5498) - 20 Jan 2015 09:48
C
C  Differentiation of flux_face in reverse (adjoint) mode:
C   gradient     of useful results: res1 res2 q1 q2 adt1 adt2
C   with respect to varying inputs: res1 res2 q1 q2 adt1 adt2
C   RW status of diff variables: res1:in-out res2:in-out q1:incr
C                q2:incr adt1:incr adt2:incr
C
C
C
C
C
      SUBROUTINE FLUX_FACE_B(x1, x2, q1, q1b, q2, q2b, adt1, adt1b, adt2
     +                       , adt2b, res1, res1b, res2, res2b)
      IMPLICIT NONE
      REAL*8 gam, gm1, cfl, eps, mach, alpha
C
      COMMON /constants/ gam, gm1, cfl, eps, mach, alpha
C
C
      INTEGER n, r
C
      REAL*8 x1(2), x2(2), q1(4), q2(4), adt1, adt2, res1(4), res2(4), 
     +       dx, dy, mu, r1i, u1, v1, p1, vol1, r2i, u2, v2, p2, vol2, f
     +       (4)
      REAL*8 q1b(4), q2b(4), adt1b, adt2b, res1b(4), res2b(4), mub, r1ib
     +       , u1b, v1b, p1b, vol1b, r2ib, u2b, v2b, p2b, vol2b, fb(4)
      REAL*8 tempb5
      REAL*8 tempb4
      REAL*8 tempb3
      REAL*8 tempb2
      REAL*8 tempb1
      REAL*8 tempb0
      REAL*8 tempb
      INTEGER ii1
C
C
      dx = x1(1) - x2(1)
      dy = x1(2) - x2(2)
      mu = 0.5d0*(adt1+adt2)*eps
C
      r1i = 1.d0/q1(1)
      u1 = r1i*q1(2)
      v1 = r1i*q1(3)
      p1 = gm1*(q1(4)-0.5d0*r1i*(q1(2)**2+q1(3)**2))
      vol1 = u1*dy - v1*dx
C
      r2i = 1.d0/q2(1)
      u2 = r2i*q2(2)
      v2 = r2i*q2(3)
      p2 = gm1*(q2(4)-0.5d0*r2i*(q2(2)**2+q2(3)**2))
      vol2 = u2*dy - v2*dx
C
      DO ii1=1,4
        fb(ii1) = 0.0
      ENDDO
      mub = 0.0
      DO n=4,1,-1
        fb(n) = fb(n) + res1b(n) - res2b(n)
        mub = mub + (q1(n)-q2(n))*fb(n)
        q1b(n) = q1b(n) + mu*fb(n)
        q2b(n) = q2b(n) - mu*fb(n)
      ENDDO
      tempb = 0.5d0*fb(4)
      q1b(4) = q1b(4) + vol1*tempb
      q2b(4) = q2b(4) + vol2*tempb
      fb(4) = 0.D0
      tempb0 = 0.5d0*fb(3)
      q1b(3) = q1b(3) + vol1*tempb0
      q2b(3) = q2b(3) + vol2*tempb0
      fb(3) = 0.D0
      tempb2 = 0.5d0*fb(2)
      p1b = dy*tempb2 - dx*tempb0 + vol1*tempb
      p2b = dy*tempb2 - dx*tempb0 + vol2*tempb
      q1b(2) = q1b(2) + vol1*tempb2
      q2b(2) = q2b(2) + vol2*tempb2
      fb(2) = 0.D0
      tempb1 = 0.5d0*fb(1)
      vol1b = q1(3)*tempb0 + q1(1)*tempb1 + q1(2)*tempb2 + (q1(4)+p1)*
     +  tempb
      vol2b = q2(3)*tempb0 + q2(1)*tempb1 + q2(2)*tempb2 + (q2(4)+p2)*
     +  tempb
      q1b(1) = q1b(1) + vol1*tempb1
      q2b(1) = q2b(1) + vol2*tempb1
      u2b = dy*vol2b
      v2b = -(dx*vol2b)
      tempb3 = -(gm1*0.5d0*p2b)
      q2b(4) = q2b(4) + gm1*p2b
      r2ib = q2(3)*v2b + q2(2)*u2b + (q2(2)**2+q2(3)**2)*tempb3
      q2b(2) = q2b(2) + r2i*2*q2(2)*tempb3
      q2b(3) = q2b(3) + r2i*v2b + r2i*2*q2(3)*tempb3
      q2b(2) = q2b(2) + r2i*u2b
      q2b(1) = q2b(1) - r2ib/q2(1)**2
      u1b = dy*vol1b
      v1b = -(dx*vol1b)
      tempb4 = -(gm1*0.5d0*p1b)
      q1b(4) = q1b(4) + gm1*p1b
      r1ib = q1(3)*v1b + q1(2)*u1b + (q1(2)**2+q1(3)**2)*tempb4
      q1b(2) = q1b(2) + r1i*2*q1(2)*tempb4
      q1b(3) = q1b(3) + r1i*v1b + r1i*2*q1(3)*tempb4
      q1b(2) = q1b(2) + r1i*u1b
      q1b(1) = q1b(1) - r1ib/q1(1)**2
      tempb5 = eps*0.5d0*mub
      adt1b = adt1b + tempb5
      adt2b = adt2b + tempb5
      END
